import os

def get_module_root():
    return os.path.dirname(os.path.abspath(__file__))

def getenv_or_die(key: str) -> str:
    """
    >>> getenv_or_die('DEBUG')
    'false'
    >>> import pytest
    >>> with pytest.raises(ValueError):
    ...     getenv_or_die('SOME_UNKNOWN_ENV_VARIABLE')
    """
    value = os.getenv(key)
    if value is None:  # pragma: no cover
        raise ValueError(f'{key} is missing in environment')

    return value


def to_bool(value: str) -> bool:
    return value is not None and value.lower() in ('1', 'y', 'yes', 't', 'true', 'on')

def to_int(value: str) -> int:
    return int(value)

def to_double(value: str) -> float:
    return float(value)

def to_list_of_strings(value: str) -> list:
    return [item.strip() for item in value.split(',')]


VERSION = getenv_or_die('VERSION')
START_TIME = os.getenv('START_TIME', '19:00')
END_TIME = os.getenv('END_TIME', '05:00')
SERVICE = getenv_or_die('SERVICE')
STAGE = getenv_or_die('STAGE')
DEBUG = to_bool(os.getenv('DEBUG'))
CLOUD_PROVIDER = getenv_or_die('CLOUD_PROVIDER')
GCP_PROJECT_ID = getenv_or_die('GCP_PROJECT_ID')
GCS_BUCKET_NAME = getenv_or_die('GCS_BUCKET_NAME')
GCP_LOCATION = getenv_or_die('GCP_LOCATION')
GCP_LOCATION_2 = getenv_or_die('GCP_LOCATION_2')
GCP_LOCATION_3 = getenv_or_die('GCP_LOCATION_3')
GCP_MULTI_REGION_FIRESTORE_LOCATON = getenv_or_die('GCP_MULTI_REGION_FIRESTORE_LOCATON')
GCP_FIRESTORE_DB= getenv_or_die('GCP_FIRESTORE_DB')

CONFIG_CACHE_ENABLE = to_bool(os.getenv('CONFIG_CACHE_ENABLE', 'true'))
CONFIG_CACHE_TTL = to_int(os.getenv('CONFIG_CACHE_TTL', '60'))

GCP_DOCAI_HCC_PROCESSOR_ID = getenv_or_die('GCP_DOCAI_HCC_PROCESSOR_ID')
GCP_DOCAI_HCC_PROCESSOR_VERSION = getenv_or_die('GCP_DOCAI_HCC_PROCESSOR_VERSION')
GCP_DOCAI_SUMMARIZER_PROCESSOR_ID = getenv_or_die('GCP_DOCAI_SUMMARIZER_PROCESSOR_ID')
GCP_DOCAI_SUMMARIZER_PROCESSOR_VERSION = getenv_or_die('GCP_DOCAI_SUMMARIZER_PROCESSOR_VERSION')
GCP_DOCAI_DOC_PROCESSOR_ID= getenv_or_die('GCP_DOCAI_DOC_PROCESSOR_ID')
GCP_DOCAI_DOC_PROCESSOR_VERSION = getenv_or_die('GCP_DOCAI_DOC_PROCESSOR_VERSION')
GCP_SEARCH_AND_CONVERSATION_DATA_SOURCE_ID = getenv_or_die('GCP_SEARCH_AND_CONVERSATION_DATA_SOURCE_ID')
GCP_SEARCH_AND_CONVERSATION_FHIR_DATA_SOURCE_ID = getenv_or_die('GCP_SEARCH_AND_CONVERSATION_FHIR_DATA_SOURCE_ID')
GCP_VECTOR_SEARCH_INDEX_GCS_URI = getenv_or_die('GCP_VECTOR_SEARCH_INDEX_GCS_URI')
GCP_VECTOR_SEARCH_INDEX_NAME = getenv_or_die('GCP_VECTOR_SEARCH_INDEX_NAME')
GCP_VECTOR_SEARCH_INDEX_ENDPOINT = getenv_or_die('GCP_VECTOR_SEARCH_INDEX_ENDPOINT')
GCP_VECTOR_SEARCH_DEPLOYED_INDEX_ID = getenv_or_die('GCP_VECTOR_SEARCH_DEPLOYED_INDEX_ID')
GCP_VECTOR_SEARCH_INDEX_NAME_2 = getenv_or_die('GCP_VECTOR_SEARCH_INDEX_NAME_2')
GCP_VECTOR_SEARCH_INDEX_ENDPOINT_2 = getenv_or_die('GCP_VECTOR_SEARCH_INDEX_ENDPOINT_2')
GCP_VECTOR_SEARCH_DEPLOYED_INDEX_ID_2 = getenv_or_die('GCP_VECTOR_SEARCH_DEPLOYED_INDEX_ID_2')
VECTOR_SEARCH_PROVIDER = os.getenv('VECTOR_SEARCH_PROVIDER', 'vertexai')  # pinecone or vertexai
FHIR_SERVER_URL = getenv_or_die('FHIR_SERVER_URL')
FHIR_DATA_STORE = getenv_or_die('FHIR_DATA_STORE')
FHIR_DATA_SET = getenv_or_die('FHIR_DATA_SET')
FHIR_SEARCH_STORE_ID = getenv_or_die('FHIR_SEARCH_STORE_ID')

ORCHESTRATION_MEDICALEXTRACTION_STEP_NORMALIZATION_ENABLED = to_bool(os.getenv('ORCHESTRATION_MEDICALEXTRACTION_STEP_NORMALIZATION_ENABLED', "false"))

MEDISPAN_API_URL = os.getenv('MEDISPAN_API_URL', "https://ct.dev.wellsky.io/api/v1/drug/information/search")
MEDISPAN_STRATEGY = os.getenv('MEDISPAN_STRATEGY', "vector-search") # vector-search or medispan or medispan-cached
MEDISPAN_FILTER_STRATEGY = os.getenv('MEDISPAN_FILTER_STRATEGY', "llm")
MEDISPAN_PAGE_SIZE = to_int(os.getenv('MEDISPAN_PAGE_SIZE', '100'))
MEDISPAN_AUTH_URL = os.getenv('MEDISPAN_AUTH_URL', "https://auth.stable.wellsky.io/connect/token")
MEDISPAN_CLIENT_ID = getenv_or_die('MEDISPAN_CLIENT_ID')
MEDISPAN_CLIENT_SECRET = getenv_or_die('MEDISPAN_CLIENT_SECRET')
MEDISPAN_FILTER_ENABLED = to_bool(os.getenv('MEDISPAN_FILTER_ENABLED', 'true'))
MEDISPAN_LLM_SCORING_ENABLED = to_bool(os.getenv('MEDISPAN_LLM_SCORING_ENABLED', 'true'))
MEDISPAN_LLM_OPTIMIZEPROMPT_ENABLED = to_bool(os.getenv('MEDISPAN_LLM_OPTIMIZEPROMPT_ENABLED', 'true'))
MEDISPAN_LLM_SCORING_FOR_USER_ADDED_ENABLED = to_bool(os.getenv('MEDISPAN_LLM_SCORING_FOR_USER_ADDED_ENABLED', 'false'))
MEDISPAN_TOKEN_BACKOFF = to_list_of_strings(os.getenv("MEDISPAN_TOKEN_BACKOFF","(IR),(ER),(CR),(SR)"))

MEDISPAN_VECTOR_SEARCH_PROJECT_ID = getenv_or_die("MEDISPAN_VECTOR_SEARCH_PROJECT_ID")
MEDISPAN_VECTOR_SEARCH_REGION = os.getenv('MEDISPAN_VECTOR_SEARCH_REGION', "us-central1")
MEDISPAN_VECTOR_SEARCH_DEPLOYMENT_ID = getenv_or_die("MEDISPAN_VECTOR_SEARCH_DEPLOYMENT_ID") # medsearch_1723187204068
MEDISPAN_VECTOR_SEARCH_MODEL_NAME = os.getenv('MEDISPAN_VECTOR_SEARCH_MODEL_NAME', "text-embedding-004")
MEDISPAN_VECTOR_SEARCH_TASK = os.getenv('MEDISPAN_VECTOR_SEARCH_TASK', "RETRIEVAL_DOCUMENT")
MEDISPAN_VECTOR_SEARCH_DIMENSIONALITY = to_int(os.getenv('MEDISPAN_VECTOR_SEARCH_DIMENSIONALITY', "768"))
MEDISPAN_VECTOR_SEARCH_ENDPOINT_ID = getenv_or_die("MEDISPAN_VECTOR_SEARCH_ENDPOINT_ID")  # 7990947045466701824
MEDISPAN_VECTOR_SEARCH_DISTANCE_THRESHOLD = to_double(os.getenv("MEDISPAN_VECTOR_SEARCH_DISTANCE_THRESHOLD", "0.9"))

MEDICATION_STRENGTH_EXTRACTION_REGEX = os.getenv("MEDICATION_STRENGTH_EXTRACTION_REGEX", "\\b\\d+-?\\d*\\s*(MG|MCG|ML)\\b")
MEDICATION_MATCHING_THRESHOLD = to_double(os.getenv("MEDICATION_MATCHING_THRESHOLD", "0.9"))
MEDICATION_MATCHING_BATCH_SIZE = to_int(os.getenv("MEDICATION_MATCHING_BATCH_SIZE", "20"))
MEDICATION_MATCHING_VERSION = os.getenv("MEDICATION_MATCHING_VERSION", "2")

MEDICAL_SUMMARIZATION_API_URL = os.getenv('MEDICAL_SUMMARIZATION_API_URL', "https://healthcare.googleapis.com/v1alpha2/projects/viki-dev-app-wsky/locations/us-central1/services/medlm:summarizeClinicalRecords")
MEDICAL_SUMMARIZATION_CONFIDENCE_THRESHOLD = to_double(os.getenv("MEDICAL_SUMMARIZATION_CONFIDENCE_THRESHOLD", "0.2"))

INTEGRATION_PROJECT_NAME = getenv_or_die('INTEGRATION_PROJECT_NAME')
SELF_API = getenv_or_die('SELF_API')
QUEUE_RESOLVER_VERSION = os.getenv('QUEUE_RESOLVER_VERSION', 'v1')
CLOUDTASK_REGISTERED_APP_IDS = to_list_of_strings(os.getenv("CLOUDTASK_REGISTERED_APP_IDS", "ltc,hhh,007"))

# Cloud Task Emulator Configuration
CLOUDTASK_EMULATOR_ENABLED = to_bool(os.getenv("CLOUDTASK_EMULATOR_ENABLED", "false"))
CLOUDTASK_EMULATOR_URL = os.getenv("CLOUDTASK_EMULATOR_URL", "")  # LOCAL URL for Cloud Task Emulator, e.g., http://cloudtask-emulator:30001

# Entity Extraction Configuration
ENTITY_EXTRACTION_API_URL = getenv_or_die("ENTITY_EXTRACTION_API_URL")
ENTITY_EXTRACTION_LAUNCH_QUEUE_NAME = getenv_or_die("ENTITY_EXTRACTION_LAUNCH_QUEUE_NAME")

CLOUD_TASK_QUEUE_NAME = getenv_or_die('CLOUD_TASK_QUEUE_NAME')
CLOUD_TASK_QUEUE_NAME_2 = getenv_or_die('CLOUD_TASK_QUEUE_NAME_2')
CLOUD_TASK_QUEUE_NAME_PRIORITY = getenv_or_die('CLOUD_TASK_QUEUE_NAME_PRIORITY')
CLOUD_TASK_QUEUE_NAME_PRIORITY_2 = getenv_or_die('CLOUD_TASK_QUEUE_NAME_PRIORITY_2')
CLOUD_TASK_QUEUE_NAME_QUARANTINE = getenv_or_die('CLOUD_TASK_QUEUE_NAME_QUARANTINE')
CLOUD_TASK_QUEUE_NAME_QUARANTINE_2 = getenv_or_die('CLOUD_TASK_QUEUE_NAME_QUARANTINE_2')

CLOUD_TASK_COMMAND_QUEUE_NAME = getenv_or_die("CLOUD_TASK_COMMAND_QUEUE_NAME")
CLOUD_TASK_COMMAND_SCHEDULE_QUEUE_NAME = getenv_or_die("CLOUD_TASK_COMMAND_SCHEDULE_QUEUE_NAME")
CLOUD_TASK_COMMAND_EXTERNAL_CREATE_DOCUMENT_TASK_QUEUE_NAME = getenv_or_die("CLOUD_TASK_COMMAND_EXTERNAL_CREATE_DOCUMENT_TASK_QUEUE_NAME")

CLOUD_TASK_PUBLISH_CALLBACK_QUEUE_NAME = getenv_or_die("CLOUD_TASK_PUBLISH_CALLBACK_QUEUE_NAME")

SERVICE_ACCOUNT_EMAIL = getenv_or_die('SERVICE_ACCOUNT_EMAIL')
APPLICATION_INTEGRATION_TRIGGER_ID = getenv_or_die('APPLICATION_INTEGRATION_TRIGGER_ID')
HHH_MEDICATION_PROFILE_BASE_URL = getenv_or_die('HHH_MEDICATION_PROFILE_BASE_URL')
HHH_CLASSIFICATION_CACHE_TTL = to_int(os.getenv('HHH_CLASSIFICATION_CACHE_TTL', '43200'))

OKTA_CLIENT_ID = getenv_or_die('OKTA_CLIENT_ID')
OKTA_CLIENT_SECRET = getenv_or_die('OKTA_CLIENT_SECRET')
OKTA_AUDIENCE = getenv_or_die('OKTA_AUDIENCE')
OKTA_TOKEN_ISSUER_URL = getenv_or_die('OKTA_TOKEN_ISSUER_URL')
OKTA_VERIFY = to_bool(os.getenv('OKTA_VERIFY', 'true'))
OKTA_SERVICE_ISSUER_URL = getenv_or_die('OKTA_SERVICE_ISSUER_URL')   # The token issuer for host systems
OKTA_SERVICE_AUDIENCE = getenv_or_die('OKTA_SERVICE_AUDIENCE')   # The audience for host systems
OKTA_SCOPE = os.getenv('OKTA_SCOPE', "api.wellsky.viki.ai.paperglass")   # OAuth scope for client credentials flow

MULTIMODAL_MODEL = os.getenv("MULTIMODAL_MODEL", "gemini-1.5-flash-002")
MULTIMODAL_ADVANCED_MODEL = os.getenv("MULTIMODAL_MODEL", "gemini-1.5-pro-001")
MULTIMODAL_TEMPERATURE = to_double(os.getenv("MULTIMODAL_TEMPERATURE", "0.0")) # TODO move to Environment Variables
MULTIMODAL_TOKENS_MAX = to_int(os.getenv("MULTIMODAL_TOKENS_MAX", "8192")) # TODO move to Environment Variables
MULTIMODAL_TOP_P = to_double(os.getenv("MULTIMODAL_TOP_P", "0.95"))  # TODO move to Environment Variables

ORCHESTRATION_GRADER_STRATEGY = os.getenv("ORCHESTRATION_GRADER_STRATEGY", "procedural") # procedural | llm
ORCHESTRATION_GRADER_PERFORMGRADING_CHUNK_SIZE = to_int(os.getenv("ORCHESTRATION_GRADER_PERFORMGRADING_CHUNK_SIZE", "20"))

# Handles off hours processing of orchestration commands (times in UTC 18:00 to 08:00 CST and 19:00 to 09:00 CDT)
ORCHESTRATION_GRADER_SCHEDULE_WINDOW_ENABLED = to_bool(os.getenv("ORCHESTRATION_GRADER_SCHEDULE_WINDOW_ENABLED", "false"))
ORCHESTRATION_GRADER_SCHEDULE_WINDOW_START = os.getenv("ORCHESTRATION_GRADER_SCHEDULE_WINDOW_START", "00:00")
ORCHESTRATION_GRADER_SCHEDULE_WINDOW_END = os.getenv("ORCHESTRATION_GRADER_SCHEDULE_WINDOW_END", "14:00")
ORCHESTRATION_GRADER_SCHEDULE_OPERATION_TYPES = ["medication_grader"]

PUBSUB_EVENT_ORCHESTRATIONCOMPLETE_TOPIC = os.getenv("PUBSUB_EVENT_ORCHESTRATIONCOMPLETE_TOPIC", f"event-orchestration-complete-topic-{STAGE}")
PUBSUB_EVENT_MEDICATION_PUBLISH_TOPIC = os.getenv("PUBSUB_EVENT_MEDICATION_PUBLISH_TOPIC", f"event-medication-publish-topic-{STAGE}")
PUBSUB_COMMAND_SCHEDULEDWINDOW1_TOPIC = os.getenv("PUBSUB_COMMAND_SCHEDULEDWINDOW1_TOPIC", f"command-scheduledwindow-1-topic-{STAGE}")

EXTERNAL_API_CONNECT_TIMEOUT_SECONDS = to_int(os.getenv("EXTERNAL_API_CONNECT_TIMEOUT_SECONDS","5"))
EXTERNAL_API_SOCKET_CONNECT_TIMEOUT_SECONDS = to_int(os.getenv("EXTERNAL_API_SOCKET_CONNECT_TIMEOUT_SECONDS","5"))
EXTERNAL_API_SOCKET_READ_TIMEOUT_SECONDS = to_int(os.getenv("EXTERNAL_API_SOCKET_READ_TIMEOUT_SECONDS","5"))
AUTO_CONVERT_IMAGE_TYPES = to_list_of_strings(os.getenv("AUTO_CONVERT_IMAGE_TYPES",".jpg,.jpeg,.png,.bmp,.tiff,.ppm,.heic,.jfif"))  #PIL only supports formats PPM, PNG, JPEG, GIF, TIFF, BMP, and HEIC

FILTER_LLM_MULTIMODAL_MODEL = os.getenv("MULTIMODAL_MODEL", "gemini-1.5-pro-001")

MEDICATION_EVIDENCE_MATCH_TOKEN_SIZE_THRESHOLD = to_int(os.getenv("MEDICATION_EVIDENCE_MATCH_TOKEN_SIZE_THRESHOLD", "5"))

AUDIT_USER_UNKNOWN = "unknown"

ONBOARDING_PATIENT_LIST = to_list_of_strings(os.getenv("ONBOARDING_PATIENT_LIST","onboarding,onboarding_wizard"))

SETTINGS_MAP = {
    "MULTIMODAL_MODEL": MULTIMODAL_MODEL,
    "MULTIMODAL_ADVANCED_MODEL": MULTIMODAL_ADVANCED_MODEL,
    "MULTIMODAL_TEMPERATURE": MULTIMODAL_TEMPERATURE,
    "MULTIMODAL_TOKENS_MAX": MULTIMODAL_TOKENS_MAX,
    "MULTIMODAL_TOP_P": MULTIMODAL_TOP_P,
}

JSON_CLEANERS = [
    {"type": "regex", "match": "(\\\\)", "replace": "\\\\\\\\"}
]
USE_JSON_SAFE_LOADS = to_bool(os.getenv("USE_JSON_SAFE_LOADS", "true"))

FIRESTORE_EMULATOR_HOST = os.getenv('FIRESTORE_EMULATOR_HOST')

HHH_ATTACHMENTS_IMPORT_ENABLED= to_bool(os.getenv('HHH_ATTACHMENTS_IMPORT_ENABLED', 'false'))
HHH_ATTACHMENTS_API= os.getenv('HHH_ATTACHMENTS_API')
HHH_ATTACHMENTS_AUTH_SERVER = os.getenv('HHH_ATTACHMENTS_AUTH_SERVER')
HHH_ATTACHMENTS_CLIENT_ID = os.getenv('HHH_ATTACHMENTS_CLIENT_ID')
HHH_ATTACHMENTS_CLIENT_SECRET = os.getenv('HHH_ATTACHMENTS_CLIENT_SECRET')
HHH_ATTACHMENTS_STORAGE_OBJECT_METADATA_ENABLE = to_bool(os.getenv('HHH_ATTACHMENTS_STORAGE_OBJECT_METADATA_ENABLE', 'true'))

SCHEDULED_COMMAND_TOPICS = {
        "OFFHOURS_1": PUBSUB_COMMAND_SCHEDULEDWINDOW1_TOPIC
}

GCP_PUBSUB_PROJECT_ID = getenv_or_die('GCP_PUBSUB_PROJECT_ID')
EXTRACTION_PUBSUB_TOPIC_NAME= getenv_or_die('EXTRACTION_PUBSUB_TOPIC_NAME')

PROMPT_AUDIT_ENABLED = to_bool(os.getenv('PROMPT_AUDIT_ENABLED', 'false'))
MOCK_PROMPT_ENABLED = to_bool(os.getenv('MOCK_PROMPT_ENABLED', 'false'))

DOCUMENT_OPERATION_INSTANCE_LOG_STRATEGY = os.getenv('DOCUMENT_OPERATION_INSTANCE_LOG_STRATEGY', 'firestore')  # storage or firestore
DOCUMENT_OPERATION_INSTANCE_LOG_FALLBACK_ENABLED = to_bool(os.getenv('DOCUMENT_OPERATION_INSTANCE_LOG_FALLBACK_ENABLED', 'true'))

OTEL_SDK_DISABLED = to_bool(os.getenv('OTEL_SDK_DISABLED', 'false'))

LOGGING_USE_CUSTOM_LOGGER = to_bool(os.getenv('LOGGING_USE_CUSTOM_LOGGER', 'true'))  #Forces all logging to use the CustomLogger
LOGGING_INJECT_GLOBAL_CONTEXT_ENABLED = to_bool(os.getenv('LOGGING_INJECT_GLOBAL_CONTEXT_ENABLED', 'true')) #Injects global context into all log messages for CustomLogger
LOGGING_CHATTY_LOGGERS = to_list_of_strings(os.getenv('LOGGING_CHATTY_LOGGERS', 'acachecontrol.cache,aiocache.base,urllib3.connectionpool')) #List of loggers that should be set to DEBUG level

GCP_TRACE_ENABLED = to_bool(os.getenv('GCP_TRACE_ENABLED', 'true'))

NEW_RELIC_TRACE_ENABLED = to_bool(os.getenv('NEW_RELIC_TRACE_ENABLED', 'true'))
NEW_RELIC_TRACE_OTLP_ENDPOINT = os.getenv('NEW_RELIC_TRACE_OTLP_ENDPOINT', 'https://otlp.nr-data.net:4317')
NEW_RELIC_LICENSE_KEY = getenv_or_die('NEW_RELIC_LICENSE_KEY')

# SharePoint configuration
SHAREPOINT_CLIENT_ID = getenv_or_die('SHAREPOINT_CLIENT_ID')
SHAREPOINT_CLIENT_SECRET = getenv_or_die('SHAREPOINT_CLIENT_SECRET')

MEDICATION_EXTRACTION_RESPAWN_INFLIGHT_ENABLE = to_bool(os.getenv('MEDICATION_EXTRACTION_RESPAWN_INFLIGHT_ENABLE', 'false'))

MEDICATION_EXTRACTION_PRIORITY_DEFAULT = os.getenv("MEDICATION_EXTRACTION_PRIORITY_DEFAULT", "default")
MEDICATION_EXTRACTION_PRIORITY_NONE = os.getenv("MEDICATION_EXTRACTION_PRIORITY_NONE", "none")
MEDICATION_EXTRACTION_PRIORITY_QUARANTINE = os.getenv("MEDICATION_EXTRACTION_PRIORITY_QUARANTINE", "quarantine")
MEDICATION_EXTRACTION_PRIORITY_LIST = to_list_of_strings(os.getenv("MEDICATION_EXTRACTION_PRIORITY_LIST", "default,high"))

MEDICATION_EXTRACTION_V4_TOPIC = getenv_or_die('MEDICATION_EXTRACTION_V4_TOPIC')
MEDICATION_EXTRACTION_V4_CLOUD_TASK_QUEUE_NAME = getenv_or_die('MEDICATION_EXTRACTION_V4_CLOUD_TASK_QUEUE_NAME')
MEDICATION_EXTRACTION_V4_CLOUD_TASK_QUEUE_NAME_PRIORITY= getenv_or_die('MEDICATION_EXTRACTION_V4_CLOUD_TASK_QUEUE_NAME_PRIORITY')
MEDICATION_EXTRACTION_V4_CLOUD_TASK_QUEUE_NAME_QUARANTINE= getenv_or_die('MEDICATION_EXTRACTION_V4_CLOUD_TASK_QUEUE_NAME_QUARANTINE')

MEDICATION_EXTRACTION_V4_API_URL = getenv_or_die('MEDICATION_EXTRACTION_V4_API_URL')
MEDICATION_EXTRACTION_V4_API_DEFAULT_URL = getenv_or_die('MEDICATION_EXTRACTION_V4_API_DEFAULT_URL')
MEDICATION_EXTRACTION_V4_API_HIGH_URL = getenv_or_die('MEDICATION_EXTRACTION_V4_API_HIGH_URL')
MEDICATION_EXTRACTION_V4_API_QUARANTINE_URL = getenv_or_die('MEDICATION_EXTRACTION_V4_API_QUARANTINE_URL')

E2E_OWNER_GOLDEN_REPO_APP_ID = os.getenv('E2E_OWNER_GOLDEN_REPO_APP_ID', '007')
E2E_OWNER_GOLDEN_REPO_TENANT_ID = os.getenv('E2E_OWNER_GOLDEN_REPO_TENANT_ID', '54321')
E2E_OWNER_GOLDEN_REPO_PATIENT_ID = os.getenv('E2E_OWNER_GOLDEN_REPO_PATIENT_ID', '12ad5af81b1e49a0977bfe3b5bc6a83f') # All env will have a patient with this id
E2E_OWNER_GOLDEN_RUN_PATIENT_ID = os.getenv('E2E_OWNER_GOLDEN_RUN_PATIENT_ID', 'fd124ad7fb9847549ae39f5ca825ccce')  # All env will have a patient with this id.  Test run docs are added here

E2E_TEST_UPDATE_ENABLE = to_bool(os.getenv('E2E_TEST_UPDATE_ENABLE', 'true'))  #Allows an E2E test to be updated from the source document
E2E_TEST_ENABLE = to_bool(os.getenv('E2E_TEST_ENABLE', 'false'))  #Enables E2E testing
E2E_TEST_SAMPLE_SIZE = to_int(os.getenv('E2E_TEST_SAMPLE_SIZE', '2'))
E2E_TEST_MAX_DURATION_SECONDS = to_int(os.getenv('E2E_TEST_MAX_DURATION', '600')) # Seconds
E2E_TEST_MAX_DURATION_SECONDS_OVERRIDE = to_int(os.getenv('E2E_TEST_MAX_DURATION_OVERRIDE', '2400')) # Seconds (if longer than the test's max duration, overrides the max duration for specific tests)
E2E_TEST_RUN_PATIENT_ID = os.getenv('E3E_TEST_RUN_PATIENT_ID', 'fd124ad7fb9847549ae39f5ca825ccce')
E2E_TEST_ASSERTION_ACCURACY_GOOD_UPPER = to_double(os.getenv('E2E_TEST_ASSERTION_ACCURACY_GOOD_UPPER', '1.00'))
E2E_TEST_ASSERTION_ACCURACY_GOOD_LOWER = to_double(os.getenv('E2E_TEST_ASSERTION_ACCURACY_GOOD_LOWER', '0.85'))
E2E_TEST_ASSERTION_RECALL_GOOD_UPPER = to_double(os.getenv('E2E_TEST_ASSERTION_RECALL_GOOD_UPPER', '1.00'))
E2E_TEST_ASSERTION_RECALL_GOOD_LOWER = to_double(os.getenv('E2E_TEST_ASSERTION_RECALL_GOOD_LOWER', '0.85'))
E2E_TEST_ASSERTION_F1_GOOD_UPPER = to_double(os.getenv('E2E_TEST_ASSERTION_F1_GOOD_UPPER', '1.00'))
E2E_TEST_ASSERTION_F1_GOOD_LOWER = to_double(os.getenv('E2E_TEST_ASSERTION_F1_GOOD_LOWER', '0.85'))
E2E_TEST_TLDR_RESULTS_WINDOW_MINUTES = to_int(os.getenv('E2E_TEST_TLDR_RESULTS_WINDOW_MINUTES', '2880')) # In minutes
E2E_TEST_MEDICATION_RETRY_COUNT = to_int(os.getenv('E2E_TEST_MEDICATION_RETRY_COUNT', '10'))

PAGE_OCR_TOPIC = os.getenv('PAGE_OCR_TOPIC','page_ocr_topic')

FEATUREFLAG_COMMAND_OUTOFBAND_CLOUDTASK_ENABLED = to_bool(os.getenv('FEATUREFLAG_COMMAND_OUTOFBAND_CLOUDTASK_ENABLED', 'true'))  # Temporary feature flag to switch from eventarc to Cloud Task for out of band commands

MEDISPAN_API_BASE_URL=os.getenv("MEDISPAN_API_BASE_URL","https://ai-medispan-api-18900418456.us-east4.run.app/api/")

MEDICATION_CATALOG_DEFAULT: str = os.getenv("MEDICATION_CATALOG_DEFAULT", "medispan")
# MEDICATION_CATALOG_007: str = os.getenv("MEDICATION_CATALOG_007", "merative")
# MEDICATION_CATALOG_HHH: str = os.getenv("MEDICATION_CATALOG_HHH", "medispan")
# MEDICATION_CATALOG_LTC: str = os.getenv("MEDICATION_CATALOG_LTC", "merative")
# MEDICATION_CATALOG_MAP: dict = {
#     "default": MEDICATION_CATALOG_DEFAULT,
#     "007": MEDICATION_CATALOG_007,
#     "hhh": MEDICATION_CATALOG_HHH,
#     "ltc": MEDICATION_CATALOG_LTC
# }
