--- query firestore_sync pg_documents_raw table for last 1 hour using timestamp field and do a merge/upsert into a table "pg_documents_deduped"
CREATE TABLE IF NOT EXISTS `viki-prod-app-wsky`.`firestore_sync`.`pg_documents_deduped`
(
  `firestore_document_id` STRING,
  `active` BOOLEAN,
  `app_id` STRING,
  `created_at` STRING,
  `created_by` STRING,
  `document_operation_instance_id` STRING,
  `embedding_chunking_strategy` INTEGER,
  `embedding_strategy` INTEGER,
  `execution_id` STRING,
  `file_name` STRING,
  `id` STRING,
  `metadata` STRING,
  `metadata_campaign_id` STRING,
  `metadata_iteration_key` STRING,
  `metadata_labels` ARRAY<STRING>,
  `modified_at` STRING,
  `modified_by` STRING,
  `page_count` INTEGER,
  `pages` ARRAY<STRUCT<data STRING>>,
  `patient_id` STRING,
  `priority` STRING,
  `source` STRING,
  `source_storage_uri` STRING,
  `storage_uri` STRING,
  `tenant_id` STRING,
  `token` STRING,
  `operation_status` STRING,
  `medication_extraction_status` STRING,
  `medication_extraction_start_time` STRING,
  `medication_extraction_end_time` STRING,
  `medication_extraction_orchestration_engine_version` STRING
)
CLUSTER BY app_id, tenant_id, patient_id, modified_at;

MERGE INTO `viki-prod-app-wsky`.`firestore_sync`.`pg_documents_deduped` AS target 

USING (
  SELECT * FROM (
    SELECT 
      timestamp,
      event_id,
      document_name,
      operation,
      CAST(JSON_EXTRACT(data, '$.active') AS BOOLEAN) as data_active,
      JSON_EXTRACT_SCALAR(data, '$.app_id') as data_app_id,
      JSON_EXTRACT_SCALAR(data, '$.created_at') as data_created_at,
      JSON_EXTRACT_SCALAR(data, '$.created_by') as data_created_by,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_instance_id') as data_document_operation_instance_id,
      CAST(JSON_EXTRACT(data, '$.embedding_chunking_strategy') AS INT64) as data_embedding_chunking_strategy,
      CAST(JSON_EXTRACT(data, '$.embedding_strategy') AS INT64) as data_embedding_strategy,
      JSON_EXTRACT_SCALAR(data, '$.execution_id') as data_execution_id,
      JSON_EXTRACT_SCALAR(data, '$.file_name') as data_file_name,
      JSON_EXTRACT_SCALAR(data, '$.id') as data_id,
      JSON_EXTRACT_SCALAR(data, '$.metadata') as data_metadata,
      JSON_EXTRACT_SCALAR(data, '$.metadata.campaign_id') as data_metadata_campaign_id,
      JSON_EXTRACT_SCALAR(data, '$.metadata.iteration_key') as data_metadata_iteration_key,
      JSON_EXTRACT_ARRAY(data, '$.metadata.labels') as data_metadata_labels,
      JSON_EXTRACT_SCALAR(data, '$.modified_at') as data_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.modified_by') as data_modified_by,
      CAST(JSON_EXTRACT(data, '$.page_count') AS INT64) as data_page_count,
      ARRAY(SELECT STRUCT(med as data) FROM UNNEST(JSON_EXTRACT_ARRAY(data, '$.pages')) as med) as data_pages,
      JSON_EXTRACT_SCALAR(data, '$.patient_id') as data_patient_id,
      JSON_EXTRACT_SCALAR(data, '$.priority') as data_priority,
      JSON_EXTRACT_SCALAR(data, '$.source') as data_source,
      JSON_EXTRACT_SCALAR(data, '$.source_storage_uri') as data_source_storage_uri,
      JSON_EXTRACT_SCALAR(data, '$.storage_uri') as data_storage_uri,
      JSON_EXTRACT_SCALAR(data, '$.tenant_id') as data_tenant_id,
      JSON_EXTRACT_SCALAR(data, '$.token') as data_token,
      JSON_EXTRACT(data, '$.operation_status') as data_operation_status,
      JSON_EXTRACT(JSON_EXTRACT(data, '$.operation_status'),'$.medication_extraction.status') as data_medication_extraction_status,
      JSON_EXTRACT(JSON_EXTRACT(data, '$.operation_status'),'$.medication_extraction.start_time') as data_medication_extraction_start_time,
      JSON_EXTRACT(JSON_EXTRACT(data, '$.operation_status'),'$.medication_extraction.end_time') as data_medication_extraction_end_time,
      JSON_EXTRACT(JSON_EXTRACT(data, '$.operation_status'),'$.medication_extraction.orchestration_engine_version') as data_medication_extraction_orchestration_engine_version,
      JSON_EXTRACT(JSON_EXTRACT(data, '$.operation_status'),'$.medication_extraction.operation_instance_id') as data_medication_extraction_operation_instance_id,
      document_id,
      ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY timestamp DESC) as rn
    FROM `viki-prod-app-wsky`.`firestore_sync`.`pg_documents_raw_changelog`
    WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
  ) 
  WHERE rn = 1
) AS source 

ON target.firestore_document_id = source.document_id

WHEN MATCHED AND TIMESTAMP(target.modified_at) < TIMESTAMP(source.data_modified_at) THEN 
  UPDATE SET
      target.active = source.data_active,
      target.app_id = source.data_app_id,
      target.created_at = source.data_created_at,
      target.created_by = source.data_created_by,
      target.document_operation_instance_id = source.data_document_operation_instance_id,
      target.embedding_chunking_strategy = source.data_embedding_chunking_strategy,
      target.embedding_strategy = source.data_embedding_strategy,
      target.execution_id = source.data_execution_id,
      target.file_name = source.data_file_name,
      target.id = source.data_id,
      target.metadata = source.data_metadata,
      target.metadata_campaign_id = source.data_metadata_campaign_id,
      target.metadata_iteration_key = source.data_metadata_iteration_key,
      target.metadata_labels = source.data_metadata_labels,
      target.modified_at = source.data_modified_at,
      target.modified_by = source.data_modified_by,
      target.page_count = source.data_page_count,
      target.pages = source.data_pages,
      target.patient_id = source.data_patient_id,
      target.priority = source.data_priority,
      target.source = source.data_source,
      target.source_storage_uri = source.data_source_storage_uri,
      target.storage_uri = source.data_storage_uri,
      target.tenant_id = source.data_tenant_id,
      target.token = source.data_token,
      target.operation_status = source.data_operation_status,
      target.medication_extraction_status = source.data_medication_extraction_status,
      target.medication_extraction_start_time = source.data_medication_extraction_start_time,
      target.medication_extraction_end_time = source.data_medication_extraction_end_time,
      target.medication_extraction_orchestration_engine_version = source.data_medication_extraction_orchestration_engine_version

WHEN NOT MATCHED THEN 
  INSERT (
    firestore_document_id,
    active,
    app_id,
    created_at,
    created_by,
    document_operation_instance_id,
    embedding_chunking_strategy,
    embedding_strategy,
    execution_id,
    file_name,
    id,
    metadata,
    metadata_campaign_id,
    metadata_iteration_key,
    metadata_labels,
    modified_at,
    modified_by,
    page_count,
    pages,
    patient_id,
    priority,
    source,
    source_storage_uri,
    storage_uri,
    tenant_id,
    token,
    operation_status,
    medication_extraction_status,
    medication_extraction_start_time,
    medication_extraction_end_time,
    medication_extraction_orchestration_engine_version
  ) 
  VALUES (
    document_id,
    source.data_active,
    source.data_app_id,
    source.data_created_at,
    source.data_created_by,
    source.data_document_operation_instance_id,
    source.data_embedding_chunking_strategy,
    source.data_embedding_strategy,
    source.data_execution_id,
    source.data_file_name,
    source.data_id,
    source.data_metadata,
    source.data_metadata_campaign_id,
    source.data_metadata_iteration_key,
    source.data_metadata_labels,
    source.data_modified_at,
    source.data_modified_by,
    source.data_page_count,
    source.data_pages,
    source.data_patient_id,
    source.data_priority,
    source.data_source,
    source.data_source_storage_uri,
    source.data_storage_uri,
    source.data_tenant_id,
    source.data_token,
    source.data_operation_status,
    source.data_medication_extraction_status,
    source.data_medication_extraction_start_time,
    source.data_medication_extraction_end_time,
    source.data_medication_extraction_orchestration_engine_version
  );
