@host_local = http://127.0.0.1:14000
@host_dev = https://ai-admin-api-zqftmopgsq-uk.a.run.app
@host_qa = https://ai-admin-api-p32qledfyq-uk.a.run.app
@host_stage = https://ai-admin-api-zzygbs3ypa-uk.a.run.app
@host_prod = https://ai-admin-api-cocynqqo6a-uk.a.run.app

@host = {{host_prod}}

# Test token for 007 app, tenant 54321, patient c211f67a0a594ceab691e566b8b37c32
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjE3ZjBmMGYxNGU5Y2FmYTlhYjUxODAxNTBhZTcxNGM5ZmQxYjVjMjYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA3NDgxMDY3MjcwMzQ2MDk5MjM1IiwiaGQiOiJ3ZWxsc2t5LmNvbSIsImVtYWlsIjoiZXJpYy5jb2luZXJAd2VsbHNreS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IjlPYmo2Tmx6Vk1CeEtGdHBLb09vOEEiLCJpYXQiOjE3NTk0MTEwMzIsImV4cCI6MTc1OTQxNDYzMn0.BTRSbtSezFgvSj2uS2qUfJi8wvHZVOVeV63uJhn22lOt4HEmEeoa2--kfm4d7Lpv6Hc45eZiiTpi1jC1WaSLP9HGNMjpalye3E-ul6doWoBieBDeD21f54m-52ZX8PNHdqIkFnwBq3HSB088BsPqqjekkA3LG01B_u0bazibA2FsL5tAhw6QtNLClLqNwZ29DxYSDj-MUCRXZZ14u69WpjBYaqthn8Mps4h-9-cCKowwmpJNOF0GAifwoy9yl17B4MIWmIAPi0CbN9W6yh1kGt0YkXqjxBJqiruryTou9UC3OMn8WZgN_3FomM_czeqnZhuRExCd8nqsJfnkjznn-w

### App Config Tests ===================================================================

### Get App Config for App ID 007
GET {{host}}/health
Authorization: Bearer {{token}}

###
GET {{host}}/api/v1/reports/host-update-summary?app_id=hhh&start_date=2025-09-01&end_date=2025-09-30
Authorization: Bearer {{token}}

###
GET {{host}}/api/v1/reports/host-update-detail?app_id=hhh&start_date=2025-09-21&end_date=2025-09-30
Authorization: Bearer {{token}}
Content-Type: text/csv

###

POST https://wellsky-ciam.oktapreview.com/oauth2/ausajt8hv1B8S7hkh1d7/v1/token
accept: application/json
cache-control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=api.wellsky.viki.ai.paperglass&client_id=api.wellsky.viki.paperglass&client_secret=Yh-TazzuFkbtZoX1aUIukO35tn6x1DRDAVqoUBPr6_mz7TlY2d1zkWq0047JcL0Y