--- query firestore_sync pg_medications_extracted_medications_raw table for last 1 hour using timestamp field and do a merge/upsert into a table "pg_medications_extracted_medications_deduped"
CREATE TABLE IF NOT EXISTS `viki-env-app-wsky`.`firestore_sync`.`pg_medications_extracted_medications_deduped`
(
  `firestore_document_id` STRING,
  `active` BOOLEAN,
  `app_id` STRING,
  `change_sets` ARRAY<STRING>,
  `created_at` STRING,
  `created_by` STRING,
  `deleted` BOOLEAN,
  `document_id` STRING,
  `document_operation_instance_id` STRING,
  `document_reference` STRING,
  `execution_id` STRING,
  `explaination` STRING,
  `id` STRING,
  `medication_classification` STRING,
  `medication_discontinued_date` STRING,
  `medication_dosage` STRING,
  `medication_end_date` STRING,
  `medication_form` STRING,
  `medication_frequency` STRING,
  `medication_instructions` STRING,
  `medication_is_long_standing` BOOLEAN,
  `medication_is_nonstandard_dose` BOOLEAN,
  `medication_medispan_id` STRING,
  `medication_name` STRING,
  `medication_name_original` STRING,
  `medication_route` STRING,
  `medication_start_date` STRING,
  `medication_strength` STRING,
  `medispan_id` STRING,
  `medispan_medication` STRING,
  `medispan_medication_classification` STRING,
  `medispan_medication_discontinued_date` STRING,
  `medispan_medication_dosage` STRING,
  `medispan_medication_end_date` STRING,
  `medispan_medication_form` STRING,
  `medispan_medication_frequency` STRING,
  `medispan_medication_instructions` STRING,
  `medispan_medication_is_long_standing` BOOLEAN,
  `medispan_medication_is_nonstandard_dose` BOOLEAN,
  `medispan_medication_medispan_id` STRING,
  `medispan_medication_name` STRING,
  `medispan_medication_name_original` STRING,
  `medispan_medication_route` STRING,
  `medispan_medication_start_date` STRING,
  `medispan_medication_strength` STRING,
  `medispan_status` STRING,
  `modified_at` STRING,
  `modified_by` STRING,
  `page_id` STRING,
  `page_number` INTEGER,
  `patient_id` STRING,
  `reason` STRING,
  `route` STRING,
  `score` STRING,
  `tenant_id` STRING
)
CLUSTER BY app_id, tenant_id, patient_id, modified_at;

MERGE INTO `viki-env-app-wsky`.`firestore_sync`.`pg_medications_extracted_medications_deduped` AS target 

USING (
  SELECT * FROM (
    SELECT 
      timestamp,
      event_id,
      document_name,
      operation,
      CAST(JSON_EXTRACT(data, '$.active') AS BOOLEAN) as data_active,
      JSON_EXTRACT_SCALAR(data, '$.app_id') as data_app_id,
      JSON_EXTRACT_ARRAY(data, '$.change_sets') as data_change_sets,
      JSON_EXTRACT_SCALAR(data, '$.created_at') as data_created_at,
      JSON_EXTRACT_SCALAR(data, '$.created_by') as data_created_by,
      CAST(JSON_EXTRACT(data, '$.deleted') AS BOOLEAN) as data_deleted,
      JSON_EXTRACT_SCALAR(data, '$.document_id') as data_document_id,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_instance_id') as data_document_operation_instance_id,
      JSON_EXTRACT_SCALAR(data, '$.document_reference') as data_document_reference,
      JSON_EXTRACT_SCALAR(data, '$.execution_id') as data_execution_id,
      JSON_EXTRACT_SCALAR(data, '$.explaination') as data_explaination,
      JSON_EXTRACT_SCALAR(data, '$.id') as data_id,
      JSON_EXTRACT_SCALAR(data, '$.medication.classification') as data_medication_classification,
      JSON_EXTRACT_SCALAR(data, '$.medication.discontinued_date') as data_medication_discontinued_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.dosage') as data_medication_dosage,
      JSON_EXTRACT_SCALAR(data, '$.medication.end_date') as data_medication_end_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.form') as data_medication_form,
      JSON_EXTRACT_SCALAR(data, '$.medication.frequency') as data_medication_frequency,
      JSON_EXTRACT_SCALAR(data, '$.medication.instructions') as data_medication_instructions,
      CAST(JSON_EXTRACT(data, '$.medication.is_long_standing') AS BOOLEAN) as data_medication_is_long_standing,
      CAST(JSON_EXTRACT(data, '$.medication.is_nonstandard_dose') AS BOOLEAN) as data_medication_is_nonstandard_dose,
      JSON_EXTRACT_SCALAR(data, '$.medication.medispan_id') as data_medication_medispan_id,
      JSON_EXTRACT_SCALAR(data, '$.medication.name') as data_medication_name,
      JSON_EXTRACT_SCALAR(data, '$.medication.name_original') as data_medication_name_original,
      JSON_EXTRACT_SCALAR(data, '$.medication.route') as data_medication_route,
      JSON_EXTRACT_SCALAR(data, '$.medication.start_date') as data_medication_start_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.strength') as data_medication_strength,
      JSON_EXTRACT_SCALAR(data, '$.medispan_id') as data_medispan_id,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication') as data_medispan_medication,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.classification') as data_medispan_medication_classification,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.discontinued_date') as data_medispan_medication_discontinued_date,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.dosage') as data_medispan_medication_dosage,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.end_date') as data_medispan_medication_end_date,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.form') as data_medispan_medication_form,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.frequency') as data_medispan_medication_frequency,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.instructions') as data_medispan_medication_instructions,
      CAST(JSON_EXTRACT(data, '$.medispan_medication.is_long_standing') AS BOOLEAN) as data_medispan_medication_is_long_standing,
      CAST(JSON_EXTRACT(data, '$.medispan_medication.is_nonstandard_dose') AS BOOLEAN) as data_medispan_medication_is_nonstandard_dose,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.medispan_id') as data_medispan_medication_medispan_id,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.name') as data_medispan_medication_name,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.name_original') as data_medispan_medication_name_original,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.route') as data_medispan_medication_route,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.start_date') as data_medispan_medication_start_date,
      JSON_EXTRACT_SCALAR(data, '$.medispan_medication.strength') as data_medispan_medication_strength,
      JSON_EXTRACT_SCALAR(data, '$.medispan_status') as data_medispan_status,
      JSON_EXTRACT_SCALAR(data, '$.modified_at') as data_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.modified_by') as data_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.page_id') as data_page_id,
      CAST(JSON_EXTRACT(data, '$.page_number') AS INT64) as data_page_number,
      JSON_EXTRACT_SCALAR(data, '$.patient_id') as data_patient_id,
      JSON_EXTRACT_SCALAR(data, '$.reason') as data_reason,
      JSON_EXTRACT_SCALAR(data, '$.route') as data_route,
      JSON_EXTRACT_SCALAR(data, '$.score') as data_score,
      JSON_EXTRACT_SCALAR(data, '$.tenant_id') as data_tenant_id,
      document_id,
      ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY timestamp DESC) as rn
    FROM `viki-env-app-wsky`.`firestore_sync`.`pg_medications_extracted_medications_raw_changelog`
    WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
  ) 
  WHERE rn = 1
) AS source 

ON target.firestore_document_id = source.document_id

WHEN MATCHED AND TIMESTAMP(target.modified_at) < TIMESTAMP(source.data_modified_at) THEN 
  UPDATE SET
      target.active = source.data_active,
      target.app_id = source.data_app_id,
      target.change_sets = source.data_change_sets,
      target.created_at = source.data_created_at,
      target.created_by = source.data_created_by,
      target.deleted = source.data_deleted,
      target.document_id = source.data_document_id,
      target.document_operation_instance_id = source.data_document_operation_instance_id,
      target.document_reference = source.data_document_reference,
      target.execution_id = source.data_execution_id,
      target.explaination = source.data_explaination,
      target.id = source.data_id,
      target.medication_classification = source.data_medication_classification,
      target.medication_discontinued_date = source.data_medication_discontinued_date,
      target.medication_dosage = source.data_medication_dosage,
      target.medication_end_date = source.data_medication_end_date,
      target.medication_form = source.data_medication_form,
      target.medication_frequency = source.data_medication_frequency,
      target.medication_instructions = source.data_medication_instructions,
      target.medication_is_long_standing = source.data_medication_is_long_standing,
      target.medication_is_nonstandard_dose = source.data_medication_is_nonstandard_dose,
      target.medication_medispan_id = source.data_medication_medispan_id,
      target.medication_name = source.data_medication_name,
      target.medication_name_original = source.data_medication_name_original,
      target.medication_route = source.data_medication_route,
      target.medication_start_date = source.data_medication_start_date,
      target.medication_strength = source.data_medication_strength,
      target.medispan_id = source.data_medispan_id,
      target.medispan_medication = source.data_medispan_medication,
      target.medispan_medication_classification = source.data_medispan_medication_classification,
      target.medispan_medication_discontinued_date = source.data_medispan_medication_discontinued_date,
      target.medispan_medication_dosage = source.data_medispan_medication_dosage,
      target.medispan_medication_end_date = source.data_medispan_medication_end_date,
      target.medispan_medication_form = source.data_medispan_medication_form,
      target.medispan_medication_frequency = source.data_medispan_medication_frequency,
      target.medispan_medication_instructions = source.data_medispan_medication_instructions,
      target.medispan_medication_is_long_standing = source.data_medispan_medication_is_long_standing,
      target.medispan_medication_is_nonstandard_dose = source.data_medispan_medication_is_nonstandard_dose,
      target.medispan_medication_medispan_id = source.data_medispan_medication_medispan_id,
      target.medispan_medication_name = source.data_medispan_medication_name,
      target.medispan_medication_name_original = source.data_medispan_medication_name_original,
      target.medispan_medication_route = source.data_medispan_medication_route,
      target.medispan_medication_start_date = source.data_medispan_medication_start_date,
      target.medispan_medication_strength = source.data_medispan_medication_strength,
      target.medispan_status = source.data_medispan_status,
      target.modified_at = source.data_modified_at,
      target.modified_by = source.data_modified_by,
      target.page_id = source.data_page_id,
      target.page_number = source.data_page_number,
      target.patient_id = source.data_patient_id,
      target.reason = source.data_reason,
      target.route = source.data_route,
      target.score = source.data_score,
      target.tenant_id = source.data_tenant_id

WHEN NOT MATCHED THEN 
  INSERT (
    firestore_document_id,
    active,
    app_id,
    change_sets,
    created_at,
    created_by,
    deleted,
    document_id,
    document_operation_instance_id,
    document_reference,
    execution_id,
    explaination,
    id,
    medication_classification,
    medication_discontinued_date,
    medication_dosage,
    medication_end_date,
    medication_form,
    medication_frequency,
    medication_instructions,
    medication_is_long_standing,
    medication_is_nonstandard_dose,
    medication_medispan_id,
    medication_name,
    medication_name_original,
    medication_route,
    medication_start_date,
    medication_strength,
    medispan_id,
    medispan_medication,
    medispan_medication_classification,
    medispan_medication_discontinued_date,
    medispan_medication_dosage,
    medispan_medication_end_date,
    medispan_medication_form,
    medispan_medication_frequency,
    medispan_medication_instructions,
    medispan_medication_is_long_standing,
    medispan_medication_is_nonstandard_dose,
    medispan_medication_medispan_id,
    medispan_medication_name,
    medispan_medication_name_original,
    medispan_medication_route,
    medispan_medication_start_date,
    medispan_medication_strength,
    medispan_status,
    modified_at,
    modified_by,
    page_id,
    page_number,
    patient_id,
    reason,
    route,
    score,
    tenant_id
  ) 
  VALUES (
    document_id,
    source.data_active,
    source.data_app_id,
    source.data_change_sets,
    source.data_created_at,
    source.data_created_by,
    source.data_deleted,
    source.data_document_id,
    source.data_document_operation_instance_id,
    source.data_document_reference,
    source.data_execution_id,
    source.data_explaination,
    source.data_id,
    source.data_medication_classification,
    source.data_medication_discontinued_date,
    source.data_medication_dosage,
    source.data_medication_end_date,
    source.data_medication_form,
    source.data_medication_frequency,
    source.data_medication_instructions,
    source.data_medication_is_long_standing,
    source.data_medication_is_nonstandard_dose,
    source.data_medication_medispan_id,
    source.data_medication_name,
    source.data_medication_name_original,
    source.data_medication_route,
    source.data_medication_start_date,
    source.data_medication_strength,
    source.data_medispan_id,
    source.data_medispan_medication,
    source.data_medispan_medication_classification,
    source.data_medispan_medication_discontinued_date,
    source.data_medispan_medication_dosage,
    source.data_medispan_medication_end_date,
    source.data_medispan_medication_form,
    source.data_medispan_medication_frequency,
    source.data_medispan_medication_instructions,
    source.data_medispan_medication_is_long_standing,
    source.data_medispan_medication_is_nonstandard_dose,
    source.data_medispan_medication_medispan_id,
    source.data_medispan_medication_name,
    source.data_medispan_medication_name_original,
    source.data_medispan_medication_route,
    source.data_medispan_medication_start_date,
    source.data_medispan_medication_strength,
    source.data_medispan_status,
    source.data_modified_at,
    source.data_modified_by,
    source.data_page_id,
    source.data_page_number,
    source.data_patient_id,
    source.data_reason,
    source.data_route,
    source.data_score,
    source.data_tenant_id
  );
