--- query firestore_sync pg_paperglass_document_operation_definition_raw table for last 1 hour using timestamp field and do a merge/upsert into a table "pg_paperglass_document_operation_definition_deduped"
CREATE TABLE IF NOT EXISTS `viki-env-app-wsky`.`firestore_sync`.`pg_paperglass_document_operation_definition_deduped`
(
  `firestore_document_id` STRING,
  `app_id` STRING,
  `tenant_id` STRING,
  `patient_id` STRING,
  `created_at` STRING,
  `created_by` STRING,
  `description` STRING,
  `disabled` BOOLEAN,
  `document_workflow_id` STRING,
  `id` STRING,
  `modified_at` STRING,
  `modified_by` STRING,
  `name` STRING,
  `operation_name` STRING,
  `operation_type` STRING,
  `step_config_ALLERGIES_EXTRACTION_description` STRING,
  `step_config_ALLERGIES_EXTRACTION_model` STRING,
  `step_config_ALLERGIES_EXTRACTION_prompt` STRING,
  `step_config_CLASSIFICATION_description` STRING,
  `step_config_CLASSIFICATION_description ` STRING,
  `step_config_CLASSIFICATION_model` STRING,
  `step_config_CLASSIFICATION_prompt` STRING,
  `step_config_CONDITIONS_EXTRACTION_description` STRING,
  `step_config_CONDITIONS_EXTRACTION_model` STRING,
  `step_config_CONDITIONS_EXTRACTION_prompt` STRING,
  `step_config_EVIDENCE_CREATION_description` STRING,
  `step_config_EVIDENCE_CREATION_model` STRING,
  `step_config_EVIDENCE_CREATION_prompt` STRING,
  `step_config_EXTRACTED_MEDICATION_GRADER_description` STRING,
  `step_config_EXTRACTED_MEDICATION_GRADER_model` STRING,
  `step_config_EXTRACTED_MEDICATION_GRADER_prompt` STRING,
  `step_config_IMMUNIZATIONS_EXTRACTION_description` STRING,
  `step_config_IMMUNIZATIONS_EXTRACTION_model` STRING,
  `step_config_IMMUNIZATIONS_EXTRACTION_prompt` STRING,
  `step_config_MEDICATIONS_EXTRACTION_description` STRING,
  `step_config_MEDICATIONS_EXTRACTION_model` STRING,
  `step_config_MEDICATIONS_EXTRACTION_prompt` STRING,
  `step_config_MEDISPAN_MATCHING_description` STRING,
  `step_config_MEDISPAN_MATCHING_description_alt` STRING,
  `step_config_MEDISPAN_MATCHING_model` STRING,
  `step_config_MEDISPAN_MATCHING_prompt` STRING,
  `step_config_NORMALIZE_MEDICATIONS_description` STRING,
  `step_config_NORMALIZE_MEDICATIONS_model` STRING,
  `step_config_NORMALIZE_MEDICATIONS_prompt` STRING,
  `step_config_TEXT_EXTRACTION_description` STRING,
  `step_config_TEXT_EXTRACTION_model` STRING,
  `step_config_TEXT_EXTRACTION_prompt` STRING,
  `step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_description` STRING,
  `step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_model` STRING,
  `step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_prompt` STRING
)
CLUSTER BY app_id, tenant_id, patient_id, modified_at;

MERGE INTO `viki-env-app-wsky`.`firestore_sync`.`pg_paperglass_document_operation_definition_deduped` AS target 

USING (
  SELECT * FROM (
    SELECT 
      timestamp,
      event_id,
      document_name,
      operation,
      JSON_EXTRACT_SCALAR(data, '$.created_at') as data_created_at,
      JSON_EXTRACT_SCALAR(data, '$.created_by') as data_created_by,
      JSON_EXTRACT_SCALAR(data, '$.description') as data_description,
      CAST(JSON_EXTRACT(data, '$.disabled') AS BOOLEAN) as data_disabled,
      JSON_EXTRACT_SCALAR(data, '$.document_workflow_id') as data_document_workflow_id,
      JSON_EXTRACT_SCALAR(data, '$.id') as data_id,
      JSON_EXTRACT_SCALAR(data, '$.modified_at') as data_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.modified_by') as data_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.name') as data_name,
      JSON_EXTRACT_SCALAR(data, '$.operation_name') as data_operation_name,
      JSON_EXTRACT_SCALAR(data, '$.operation_type') as data_operation_type,
      JSON_EXTRACT_SCALAR(data, '$.step_config.ALLERGIES_EXTRACTION.description') as data_step_config_ALLERGIES_EXTRACTION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.ALLERGIES_EXTRACTION.model') as data_step_config_ALLERGIES_EXTRACTION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.ALLERGIES_EXTRACTION.prompt') as data_step_config_ALLERGIES_EXTRACTION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CLASSIFICATION.description') as data_step_config_CLASSIFICATION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CLASSIFICATION.description ') as data_step_config_CLASSIFICATION_description ,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CLASSIFICATION.model') as data_step_config_CLASSIFICATION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CLASSIFICATION.prompt') as data_step_config_CLASSIFICATION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CONDITIONS_EXTRACTION.description') as data_step_config_CONDITIONS_EXTRACTION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CONDITIONS_EXTRACTION.model') as data_step_config_CONDITIONS_EXTRACTION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.CONDITIONS_EXTRACTION.prompt') as data_step_config_CONDITIONS_EXTRACTION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.EVIDENCE_CREATION.description') as data_step_config_EVIDENCE_CREATION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.EVIDENCE_CREATION.model') as data_step_config_EVIDENCE_CREATION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.EVIDENCE_CREATION.prompt') as data_step_config_EVIDENCE_CREATION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.EXTRACTED_MEDICATION_GRADER.description') as data_step_config_EXTRACTED_MEDICATION_GRADER_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.EXTRACTED_MEDICATION_GRADER.model') as data_step_config_EXTRACTED_MEDICATION_GRADER_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.EXTRACTED_MEDICATION_GRADER.prompt') as data_step_config_EXTRACTED_MEDICATION_GRADER_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.IMMUNIZATIONS_EXTRACTION.description') as data_step_config_IMMUNIZATIONS_EXTRACTION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.IMMUNIZATIONS_EXTRACTION.model') as data_step_config_IMMUNIZATIONS_EXTRACTION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.IMMUNIZATIONS_EXTRACTION.prompt') as data_step_config_IMMUNIZATIONS_EXTRACTION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDICATIONS_EXTRACTION.description') as data_step_config_MEDICATIONS_EXTRACTION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDICATIONS_EXTRACTION.model') as data_step_config_MEDICATIONS_EXTRACTION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDICATIONS_EXTRACTION.prompt') as data_step_config_MEDICATIONS_EXTRACTION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDISPAN_MATCHING.description') as data_step_config_MEDISPAN_MATCHING_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDISPAN_MATCHING.description_alt') as data_step_config_MEDISPAN_MATCHING_description_alt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDISPAN_MATCHING.model') as data_step_config_MEDISPAN_MATCHING_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.MEDISPAN_MATCHING.prompt') as data_step_config_MEDISPAN_MATCHING_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.NORMALIZE_MEDICATIONS.description') as data_step_config_NORMALIZE_MEDICATIONS_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.NORMALIZE_MEDICATIONS.model') as data_step_config_NORMALIZE_MEDICATIONS_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.NORMALIZE_MEDICATIONS.prompt') as data_step_config_NORMALIZE_MEDICATIONS_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.TEXT_EXTRACTION.description') as data_step_config_TEXT_EXTRACTION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.TEXT_EXTRACTION.model') as data_step_config_TEXT_EXTRACTION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.TEXT_EXTRACTION.prompt') as data_step_config_TEXT_EXTRACTION_prompt,
      JSON_EXTRACT_SCALAR(data, '$.step_config.TEXT_EXTRACTION_AND_CLASSIFICATION.description') as data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_description,
      JSON_EXTRACT_SCALAR(data, '$.step_config.TEXT_EXTRACTION_AND_CLASSIFICATION.model') as data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_model,
      JSON_EXTRACT_SCALAR(data, '$.step_config.TEXT_EXTRACTION_AND_CLASSIFICATION.prompt') as data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_prompt,
      document_id,
      ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY timestamp DESC) as rn
    FROM `viki-env-app-wsky`.`firestore_sync`.`pg_paperglass_document_operation_definition_raw_changelog`
    WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
  ) 
  WHERE rn = 1
) AS source 

ON target.firestore_document_id = source.document_id

WHEN MATCHED AND TIMESTAMP(target.modified_at) < TIMESTAMP(source.data_modified_at) THEN 
  UPDATE SET
      target.created_at = source.data_created_at,
      target.created_by = source.data_created_by,
      target.description = source.data_description,
      target.disabled = source.data_disabled,
      target.document_workflow_id = source.data_document_workflow_id,
      target.id = source.data_id,
      target.modified_at = source.data_modified_at,
      target.modified_by = source.data_modified_by,
      target.name = source.data_name,
      target.operation_name = source.data_operation_name,
      target.operation_type = source.data_operation_type,
      target.step_config_ALLERGIES_EXTRACTION_description = source.data_step_config_ALLERGIES_EXTRACTION_description,
      target.step_config_ALLERGIES_EXTRACTION_model = source.data_step_config_ALLERGIES_EXTRACTION_model,
      target.step_config_ALLERGIES_EXTRACTION_prompt = source.data_step_config_ALLERGIES_EXTRACTION_prompt,
      target.step_config_CLASSIFICATION_description = source.data_step_config_CLASSIFICATION_description,
      target.step_config_CLASSIFICATION_description  = source.data_step_config_CLASSIFICATION_description ,
      target.step_config_CLASSIFICATION_model = source.data_step_config_CLASSIFICATION_model,
      target.step_config_CLASSIFICATION_prompt = source.data_step_config_CLASSIFICATION_prompt,
      target.step_config_CONDITIONS_EXTRACTION_description = source.data_step_config_CONDITIONS_EXTRACTION_description,
      target.step_config_CONDITIONS_EXTRACTION_model = source.data_step_config_CONDITIONS_EXTRACTION_model,
      target.step_config_CONDITIONS_EXTRACTION_prompt = source.data_step_config_CONDITIONS_EXTRACTION_prompt,
      target.step_config_EVIDENCE_CREATION_description = source.data_step_config_EVIDENCE_CREATION_description,
      target.step_config_EVIDENCE_CREATION_model = source.data_step_config_EVIDENCE_CREATION_model,
      target.step_config_EVIDENCE_CREATION_prompt = source.data_step_config_EVIDENCE_CREATION_prompt,
      target.step_config_EXTRACTED_MEDICATION_GRADER_description = source.data_step_config_EXTRACTED_MEDICATION_GRADER_description,
      target.step_config_EXTRACTED_MEDICATION_GRADER_model = source.data_step_config_EXTRACTED_MEDICATION_GRADER_model,
      target.step_config_EXTRACTED_MEDICATION_GRADER_prompt = source.data_step_config_EXTRACTED_MEDICATION_GRADER_prompt,
      target.step_config_IMMUNIZATIONS_EXTRACTION_description = source.data_step_config_IMMUNIZATIONS_EXTRACTION_description,
      target.step_config_IMMUNIZATIONS_EXTRACTION_model = source.data_step_config_IMMUNIZATIONS_EXTRACTION_model,
      target.step_config_IMMUNIZATIONS_EXTRACTION_prompt = source.data_step_config_IMMUNIZATIONS_EXTRACTION_prompt,
      target.step_config_MEDICATIONS_EXTRACTION_description = source.data_step_config_MEDICATIONS_EXTRACTION_description,
      target.step_config_MEDICATIONS_EXTRACTION_model = source.data_step_config_MEDICATIONS_EXTRACTION_model,
      target.step_config_MEDICATIONS_EXTRACTION_prompt = source.data_step_config_MEDICATIONS_EXTRACTION_prompt,
      target.step_config_MEDISPAN_MATCHING_description = source.data_step_config_MEDISPAN_MATCHING_description,
      target.step_config_MEDISPAN_MATCHING_description_alt = source.data_step_config_MEDISPAN_MATCHING_description_alt,
      target.step_config_MEDISPAN_MATCHING_model = source.data_step_config_MEDISPAN_MATCHING_model,
      target.step_config_MEDISPAN_MATCHING_prompt = source.data_step_config_MEDISPAN_MATCHING_prompt,
      target.step_config_NORMALIZE_MEDICATIONS_description = source.data_step_config_NORMALIZE_MEDICATIONS_description,
      target.step_config_NORMALIZE_MEDICATIONS_model = source.data_step_config_NORMALIZE_MEDICATIONS_model,
      target.step_config_NORMALIZE_MEDICATIONS_prompt = source.data_step_config_NORMALIZE_MEDICATIONS_prompt,
      target.step_config_TEXT_EXTRACTION_description = source.data_step_config_TEXT_EXTRACTION_description,
      target.step_config_TEXT_EXTRACTION_model = source.data_step_config_TEXT_EXTRACTION_model,
      target.step_config_TEXT_EXTRACTION_prompt = source.data_step_config_TEXT_EXTRACTION_prompt,
      target.step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_description = source.data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_description,
      target.step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_model = source.data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_model,
      target.step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_prompt = source.data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_prompt

WHEN NOT MATCHED THEN 
  INSERT (
    firestore_document_id,
    created_at,
    created_by,
    description,
    disabled,
    document_workflow_id,
    id,
    modified_at,
    modified_by,
    name,
    operation_name,
    operation_type,
    step_config_ALLERGIES_EXTRACTION_description,
    step_config_ALLERGIES_EXTRACTION_model,
    step_config_ALLERGIES_EXTRACTION_prompt,
    step_config_CLASSIFICATION_description,
    step_config_CLASSIFICATION_description ,
    step_config_CLASSIFICATION_model,
    step_config_CLASSIFICATION_prompt,
    step_config_CONDITIONS_EXTRACTION_description,
    step_config_CONDITIONS_EXTRACTION_model,
    step_config_CONDITIONS_EXTRACTION_prompt,
    step_config_EVIDENCE_CREATION_description,
    step_config_EVIDENCE_CREATION_model,
    step_config_EVIDENCE_CREATION_prompt,
    step_config_EXTRACTED_MEDICATION_GRADER_description,
    step_config_EXTRACTED_MEDICATION_GRADER_model,
    step_config_EXTRACTED_MEDICATION_GRADER_prompt,
    step_config_IMMUNIZATIONS_EXTRACTION_description,
    step_config_IMMUNIZATIONS_EXTRACTION_model,
    step_config_IMMUNIZATIONS_EXTRACTION_prompt,
    step_config_MEDICATIONS_EXTRACTION_description,
    step_config_MEDICATIONS_EXTRACTION_model,
    step_config_MEDICATIONS_EXTRACTION_prompt,
    step_config_MEDISPAN_MATCHING_description,
    step_config_MEDISPAN_MATCHING_description_alt,
    step_config_MEDISPAN_MATCHING_model,
    step_config_MEDISPAN_MATCHING_prompt,
    step_config_NORMALIZE_MEDICATIONS_description,
    step_config_NORMALIZE_MEDICATIONS_model,
    step_config_NORMALIZE_MEDICATIONS_prompt,
    step_config_TEXT_EXTRACTION_description,
    step_config_TEXT_EXTRACTION_model,
    step_config_TEXT_EXTRACTION_prompt,
    step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_description,
    step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_model,
    step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_prompt
  ) 
  VALUES (
    document_id,
    source.data_created_at,
    source.data_created_by,
    source.data_description,
    source.data_disabled,
    source.data_document_workflow_id,
    source.data_id,
    source.data_modified_at,
    source.data_modified_by,
    source.data_name,
    source.data_operation_name,
    source.data_operation_type,
    source.data_step_config_ALLERGIES_EXTRACTION_description,
    source.data_step_config_ALLERGIES_EXTRACTION_model,
    source.data_step_config_ALLERGIES_EXTRACTION_prompt,
    source.data_step_config_CLASSIFICATION_description,
    source.data_step_config_CLASSIFICATION_description ,
    source.data_step_config_CLASSIFICATION_model,
    source.data_step_config_CLASSIFICATION_prompt,
    source.data_step_config_CONDITIONS_EXTRACTION_description,
    source.data_step_config_CONDITIONS_EXTRACTION_model,
    source.data_step_config_CONDITIONS_EXTRACTION_prompt,
    source.data_step_config_EVIDENCE_CREATION_description,
    source.data_step_config_EVIDENCE_CREATION_model,
    source.data_step_config_EVIDENCE_CREATION_prompt,
    source.data_step_config_EXTRACTED_MEDICATION_GRADER_description,
    source.data_step_config_EXTRACTED_MEDICATION_GRADER_model,
    source.data_step_config_EXTRACTED_MEDICATION_GRADER_prompt,
    source.data_step_config_IMMUNIZATIONS_EXTRACTION_description,
    source.data_step_config_IMMUNIZATIONS_EXTRACTION_model,
    source.data_step_config_IMMUNIZATIONS_EXTRACTION_prompt,
    source.data_step_config_MEDICATIONS_EXTRACTION_description,
    source.data_step_config_MEDICATIONS_EXTRACTION_model,
    source.data_step_config_MEDICATIONS_EXTRACTION_prompt,
    source.data_step_config_MEDISPAN_MATCHING_description,
    source.data_step_config_MEDISPAN_MATCHING_description_alt,
    source.data_step_config_MEDISPAN_MATCHING_model,
    source.data_step_config_MEDISPAN_MATCHING_prompt,
    source.data_step_config_NORMALIZE_MEDICATIONS_description,
    source.data_step_config_NORMALIZE_MEDICATIONS_model,
    source.data_step_config_NORMALIZE_MEDICATIONS_prompt,
    source.data_step_config_TEXT_EXTRACTION_description,
    source.data_step_config_TEXT_EXTRACTION_model,
    source.data_step_config_TEXT_EXTRACTION_prompt,
    source.data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_description,
    source.data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_model,
    source.data_step_config_TEXT_EXTRACTION_AND_CLASSIFICATION_prompt
  );
