FROM node:20.11.0-bookworm-slim

WORKDIR /medwidget

ADD package.json package-lock.json tsconfig.json .eslintrc ./

RUN --mount=type=secret,id=npmrc,target=/medwidget/.npmrc npm i

COPY src src
COPY public public
ADD craco.config.js .eslintrc .

ENV PORT=16001
# ENV REACT_APP_PUBLIC_URL=http://localhost:15001
# ENV PUBLIC_URL=http://localhost:15001
CMD ["npm", "start"]
