FROM node:20.11.0-bookworm-slim

WORKDIR /dashboard

ADD package.json package-lock.json tsconfig.json ./

RUN --mount=type=secret,id=npmrc,target=/dashboard/.npmrc npm i

COPY src src
COPY public public
ADD config-overrides.js .

ENV PORT=13001
CMD ["npm", "start"]
