from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class Text(BaseModel):
    content: str
    begin_offset: int


class Value(BaseModel):
    value: str
    confidence: float


class Mention(BaseModel):
    id: str
    type: str
    text: Text
    linked_entities: List[str]
    temporal_assessment: Optional[Value]
    certainty_assessment: Optional[Value]
    subject: Optional[Value]
    confidence: float


class Entity(BaseModel):
    id: str
    preferred_term: str
    vocabulary_codes: List[str]


class Relationship(BaseModel):
    subject_id: str
    object_id: str
    confidence: float


class EntityType(Enum):
    """
    Generated by ChatGPT from https://cloud.google.com/healthcare-api/docs/concepts/nlp#supported-medical

    Original query:

        Generate one Python enum class for the following entities using the following example:

        ```
        class EntityType(Enum):
            ANATOMICAL_STRUCTURE = "ANATOMICAL_STRUCTURE"  # A complex part of the human body, such as cells, organs, and systems.
        ```


        ANATOMICAL_STRUCTURE	A complex part of the human body, such as cells, organs, and systems.
        BODY_FUNCTION	A function carried out by the human body.
        [... remaining text omitted for brevity ...]
    """

    ANATOMICAL_STRUCTURE = (
        "ANATOMICAL_STRUCTURE"  # A complex part of the human body, such as cells, organs, and systems.
    )
    BODY_FUNCTION = "BODY_FUNCTION"  # A function carried out by the human body.
    BF_RESULT = "BF_RESULT"  # The result of a body function.
    BODY_MEASUREMENT = "BODY_MEASUREMENT"  # A normal measurement of the human body, such as vital signs, obtained without any complex tests or procedures using basic instruments, such as a thermometer or a stethoscope.
    BM_RESULT = "BM_RESULT"  # The result of a body measurement.
    BM_UNIT = "BM_UNIT"  # The unit for a body measurement.
    BM_VALUE = "BM_VALUE"  # The value of a body measurement.
    DATE = (
        "DATE"  # A date annotation, such as the date of diagnosis, date of procedure, or date of a radiation treatment.
    )
    LABORATORY_DATA = "LABORATORY_DATA"  # The results of testing a bodily sample.
    LAB_SPECIMEN = "LAB_SPECIMEN"  # Biological material collected from the body for testing or sampling.
    LAB_RESULT = "LAB_RESULT"  # A qualitative description of laboratory data, such as "increased", "decreased", "positive", or "negative".
    LAB_VALUE = "LAB_VALUE"  # The value of an instance of the laboratory data.
    LAB_UNIT = "LAB_UNIT"  # The unit of measurement for the laboratory value.
    MEDICAL_DEVICE = "MEDICAL_DEVICE"  # A physical or virtual instrument.
    MEDICINE = "MEDICINE"  # A drug or other preparation for the treatment or prevention of a disease.
    MED_DOSE = "MED_DOSE"  # A dose of a medication.
    MED_DURATION = "MED_DURATION"  # The period of administration of a medication.
    MED_FORM = "MED_FORM"  # The physical characteristics of a specific medication.
    MED_FREQUENCY = "MED_FREQUENCY"  # The frequency at which a medication is taken.
    MED_ROUTE = "MED_ROUTE"  # A location in the body where a medication is administered.
    MED_STATUS = "MED_STATUS"  # The status of an existing medication, such as "continue", "start", "restart", "stop", "switch", "increase", and "decrease".
    MED_STRENGTH = "MED_STRENGTH"  # The amount of active ingredient in a dose of a medication.
    MED_UNIT = "MED_UNIT"  # The unit of measurement for the active ingredient in a medication.
    MED_TOTALDOSE = "MED_TOTALDOSE"  # The quantity of medication to take at one time.
    PROBLEM = "PROBLEM"  # A medical condition, including findings and diseases.
    PROCEDURE = "PROCEDURE"  # A diagnostic or treatment procedure.
    PROCEDURE_RESULT = "PROCEDURE_RESULT"  # The results of a procedure.
    PROC_METHOD = "PROC_METHOD"  # The method used to conduct a procedure.
    SEVERITY = "SEVERITY"  # The severity of the medical condition.
    SUBSTANCE_ABUSE = "SUBSTANCE_ABUSE"  # A description of abuse of a psychoactive substance.
    CLINICAL_STATUS = (
        "CLINICAL_STATUS"  # The status of a cancer case such as "active", "recurring", "relapsing", and "resolved".
    )
    DIMENSIONS = "DIMENSIONS"  # The measurements of a tumor, a mass, or an abnormal growth.
    GENE_STUDIED = "GENE_STUDIED"  # The genes studied which directly or indirectly lead to tumor formation, such as BRCA1, p53, and ALK.
    HISTOLOGICAL_GRADE = "HISTOLOGICAL_GRADE"  # A classification system to grade the appearance of a cancerous cell.
    RADIATION_DOSAGE = "RADIATION_DOSAGE"  # The amount of radiation given to a patient.
    ONSET = "ONSET"  # A date annotation to represent the date when a patient first observed cancer-related problems.
    VARIATION_CODE = "VARIATION_CODE"  # A code given to the specific genomic variant that's detected under a major coding system such as Clinvar and HGVS.


class Feature(BaseModel):
    mention: Mention
    related_mentions: List[Mention]


class ExtractResult(BaseModel):
    mentions: List[Mention]
    problems: List[Feature]
    medicines: List[Feature]
    procedures: List[Feature]
