
## gcloud auth get-identity-token
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImUxNGMzN2Q2ZTVjNzU2ZThiNzJmZGI1MDA0YzBjYzM1NjMzNzkyNGUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA3NDgxMDY3MjcwMzQ2MDk5MjM1IiwiaGQiOiJ3ZWxsc2t5LmNvbSIsImVtYWlsIjoiZXJpYy5jb2luZXJAd2VsbHNreS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IlpPQUtIb0lfd29GcnF4NW9HTnFIMnciLCJpYXQiOjE3NDczMjM5MzgsImV4cCI6MTc0NzMyNzUzOH0.UP6Oy-BscuPb0a_7H0KXfsuOPm7phbGLmZIq-1IYeMMG8_UGicQPzE1Aw09wVlS4ouEVsUwlJEjS-kU-l-LfJwyXoGVRA29pQ3jPJqScpVYN71jr5fo6KNzxSfYXKuvfSw7jVY26RFgas488aIytz5nW5FZ-bYk-bXDGMy5e0qvvRM4yfD1l2BYgjzUNzRQ4hCrbP36I8c5o7JfJf2p36umrW_qwAkea5FhkZDva9uVN0EB4_kJJ26Fxwpne8jsSaZUFuL326_OOWqA4qaRwH5sBLeNN3YUMw9FcHRdpfD1S6D8Vj2y_mThuaeYgs9Z02-MSgBj74n1RypFaSYpSMQ

### Medispan Drugs API
GET https://ai-medispan-api-145042810266.us-east4.run.app/api/medispan/drugs/search?query=Asp&similarity_threshold=0.7&top_k=10
Authorization: Bearer {{token}}

### Merative Drugs API
GET https://ai-medispan-api-145042810266.us-east4.run.app/api/merative/drugs/search?query=Asp&similarity_threshold=0.7&top_k=10
Authorization: Bearer {{token}}
