@host_local = http://127.0.0.1:15000
@host_dev = https://ai-paperglass-api-secondary-zqftmopgsq-uk.a.run.app
@host_qa = https://ai-paperglass-api-p32qledfyq-uk.a.run.app
@host_stage = https://ai-paperglass-api-zzygbs3ypa-uk.a.run.app
@host_prod = https://ai-paperglass-api-cocynqqo6a-uk.a.run.app
# https://ai-paperglass-api-secondary-cocynqqo6a-uk.a.run.app

@host = {{host_dev}}

#hhh 13140 16948166  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImhoaCIsInRlbmFudElkIjoiMTMxNDAiLCJwYXRpZW50SWQiOiIxNjk0ODE2NiIsImFtdXNlcmtleSI6IjEyMzQ1In0.bt_bEdq5ARyZRt6KaC50dearDPPViOpRxPLPiigcGKQ
#ltc eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6Imx0YyIsInRlbmFudElkIjoiMDAyMzI5OkZDMzQiLCJwYXRpZW50SWQiOiIyODY2IiwiYW11c2Vya2V5IjoiMTIzNDUifQ.MZc7zOy6zWpORzEh_7P9bkLtgDBrd1QLGVfQfuzkkP0
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6Imx0YyIsInRlbmFudElkIjoiMDAyMzI5OkZDMzQiLCJwYXRpZW50SWQiOiIyODY2IiwiYW11c2Vya2V5IjoiMTIzNDUifQ.MZc7zOy6zWpORzEh_7P9bkLtgDBrd1QLGVfQfuzkkP0
#Get the okta_token from the HHH app, look for initMedWidgetButton
@okta_token = eyJraWQiOiJ5VzJxcllkVjRHbDVnX2FBM3JyWGdtUkpfQ1BaMVBlbmszZ3A5QXVqQlB3IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmI3ZlBKNFRFUkZLY0YxMVhadllWSkJJaE0zZTUxd0xTdmpVYWxXSkE5WGciLCJpc3MiOiJodHRwczovL3dlbGxza3ktY2lhbS5va3RhcHJldmlldy5jb20vb2F1dGgyL2F1c2FqdDhodjFCOFM3aGtoMWQ3IiwiYXVkIjoidmlraS5wcm9kLndlbGxza3kuaW8iLCJpYXQiOjE3NDkyNDAzNDksImV4cCI6MTc0OTI0Mzk0OSwiY2lkIjoiYXBpLndlbGxza3kudmlraS5wYXBlcmdsYXNzIiwic2NwIjpbImFwaS53ZWxsc2t5LnZpa2kuYWkucGFwZXJnbGFzcyJdLCJzdWIiOiJhcGkud2VsbHNreS52aWtpLnBhcGVyZ2xhc3MifQ.xDdVX1JhETDxO5gGu9o_KPD9nXhSCZSkhBaFyM1I2lt71jrkA4SRI0ZQyJVpzP6SF-ygUyMcB7FFbem-ieryyG_okIaQNzzY050smDlFw49On_QMSLoqHywzrTWQh6IrCRWs5q9DqdWkl9Zp-JWStEzh332jxp54SYDpVIjZZhPaPZbynE8fGIqivZ3rk-aHQYodV6cswuWrekeeAUO7utXimm3d23q2x9iKdLSTqnpjbxiBfpufYCNp4afo1mWcLBj60wjJyef7WHW_rVOCDmgkscd2icV8qsGN93TLBYlpVATFmETC-ObHe8tkiAGMUx-ov6cow5Kfb3VGMKCg7A


###
GET {{host}}/api/status/token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InFWaXRxWlhsVC1OU3hGb3V5QW1rZHg3VTZSR2lORnBBOWg5ZUlna3dCbVEiLCJ0eXAiOiJKV1QifQ.eyJhcHBJZCI6Imx0YyIsInRlbmFudElkIjoiMDAyMzI5OkZDMzQiLCJwYXRpZW50SWQiOiIzNjgiLCJ1c2VySWQiOiJzdXBwb3J0IiwiaXNzIjoiaHR0cHM6Ly9tZWRleHRyYWN0LXFhLmV4cGVyaWVuY2UuY2FyZS9hcGkvdjEvbWVkZXgiLCJpYXQiOiIxNzUyODYzNDA5IiwiZXhwIjoxNzUyODc3ODA5LCJzdWIiOiJzdXBwb3J0IiwibmJmIjoxNzUyODYzNDA5fQ.NLAM5yKilxZ7-T77VQekL90RFCPE5whzyG2p413KPhIOOaOewhlOoYH9IYgMxp0VgrF9n1SQ7PbES8lR8hxiuFrmkOqD6GuEQY3vi6GwpvRGhNLMwArIdxsKoU1MLHQ-g2iAsCi7xkWXgIv7I-xlgmdLbP9gzK9Jiln433kAyIlpOhSQfBgKPkpit5f4_AvwZeDUbr5H0tZIBdP0Ll4RE64R288lBLwfsMwWZs4yTfDc-EQoNec_xrc4zcpsY5LE60yUl7qkDkl_6DVbM6vNymuB0sFm-sz9WjnvPKNtAjWylH_yPtKZyDtaQYhZGEWw-zNBHzOx0bZJVex_OAt5gw


###
GET {{host}}/api/status/oktatoken
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InFWaXRxWlhsVC1OU3hGb3V5QW1rZHg3VTZSR2lORnBBOWg5ZUlna3dCbVEiLCJ0eXAiOiJKV1QifQ.eyJhcHBJZCI6Imx0YyIsInRlbmFudElkIjoiMDAyMzI5OkZDMzQiLCJwYXRpZW50SWQiOiIzNjgiLCJ1c2VySWQiOiJzdXBwb3J0IiwiaXNzIjoiaHR0cHM6Ly9tZWRleHRyYWN0LXFhLmV4cGVyaWVuY2UuY2FyZS9hcGkvdjEvbWVkZXgiLCJpYXQiOiIxNzUyODYzNDA5IiwiZXhwIjoxNzUyODc3ODA5LCJzdWIiOiJzdXBwb3J0IiwibmJmIjoxNzUyODYzNDA5fQ.NLAM5yKilxZ7-T77VQekL90RFCPE5whzyG2p413KPhIOOaOewhlOoYH9IYgMxp0VgrF9n1SQ7PbES8lR8hxiuFrmkOqD6GuEQY3vi6GwpvRGhNLMwArIdxsKoU1MLHQ-g2iAsCi7xkWXgIv7I-xlgmdLbP9gzK9Jiln433kAyIlpOhSQfBgKPkpit5f4_AvwZeDUbr5H0tZIBdP0Ll4RE64R288lBLwfsMwWZs4yTfDc-EQoNec_xrc4zcpsY5LE60yUl7qkDkl_6DVbM6vNymuB0sFm-sz9WjnvPKNtAjWylH_yPtKZyDtaQYhZGEWw-zNBHzOx0bZJVex_OAt5gw
okta-token: eyJraWQiOiJxVml0cVpYbFQtTlN4Rm91eUFta2R4N1U2UkdpTkZwQTloOWVJZ2t3Qm1RIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULl9DdjFkU3lhbWxUZUUyampUNFpyODhHZWlMazBDaGZNNmoyb3E1MEt1cDQiLCJpc3MiOiJodHRwczovL3dlbGxza3ktY2lhbS5va3RhcHJldmlldy5jb20vb2F1dGgyL2F1c2x4eHBtOWhyeVQyb1ZMMWQ3IiwiYXVkIjoidmlraS5kZXYud2VsbHNreS5pbyIsImlhdCI6MTc1Mjg2MDYyMCwiZXhwIjoxNzUyODY0MjIwLCJjaWQiOiJhcGkud2VsbHNreS52aWtpLnBhcGVyZ2xhc3MuZGV2Lmx0YyIsInNjcCI6WyJhcGkud2VsbHNreS52aWtpLmFpLnBhcGVyZ2xhc3MiXSwic3ViIjoiYXBpLndlbGxza3kudmlraS5wYXBlcmdsYXNzLmRldi5sdGMifQ.DzmCWd5vY0KB4rsBTw5mIBeO3XtLFlZKr_P2OSWjLnRPOvmFMhI-hWZUU2niUADRj4pR4o_iPKyCCbKjFsABhZca57qDn7FviSLv0Q98HCzv3sMVLrwZtNMXN8bigurVm4AK_qO7_tIlh1LKjvkNi4454xKtQFRBwmuRps_spRLCPPhitTe9eYrrB2xEB89wEd_Tede41KR5KkXS_cJvTTkilrP38BeJnrgOhtrC4G7zJlZb3FtguZo69CubAawd8TTx7IkcDfIbp5FGDLbERhL2L0uToIT1Wpg1YhjTU5UucIkY9ScKLV_v66JYMT_F_kt0z0lKLOoMa8GHHTHpgA




#ltc 3f6a1bee430d11f086ba42004e494300
@test_doc_id = aae159f0329b11f0a19c42004e494300
#@test_doc_id = a305b7e8329211f0b9be42004e494300

### Get page toc med "bubbles"
GET {{host}}/api/v4/documents/{{test_doc_id}}/toc/pageprofiles/medication
Authorization: Bearer {{token}}

### Get list of medications for a document
GET {{host}}/api/v4/medications_by_documents?documentVersions={%22{{test_doc_id}}%22:%22v4%22}
Authorization: Bearer {{token}}
Okta-Token: {{okta_token}}



###
GET {{host}}/api/v4/documents/c2eec868cd2c11ef98c742004e494300/toc/pageprofiles/medication
Authorization: Bearer {{token}}

### Run Medication Extraction for document --------------------------------------------------
POST {{host}}/api/orchestrate/medication_extraction
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjAwNyIsInRlbmFudElkIjoiNTQzMjEiLCJwYXRpZW50SWQiOiIyOTQzN2RkMjRmZmU0NjVlYjYxMWE2MWIwYjYyZjYwOCIsImFtdXNlcmtleSI6IjEyMzQ1In0.nNHPgG08X_YqaBN1spIKq2j0xTRT3vQmXhv-rOZ8JAU
Content-Type: application/json

{
  "document_id": "5338405c47c111f08b1242004e494300",
  "priority": "high"
}