--- query firestore_sync pg_medications_imported_medications_raw table for last 1 hour using timestamp field and do a merge/upsert into a table "pg_medications_imported_medications_deduped"
CREATE TABLE IF NOT EXISTS `viki-qa-app-wsky`.`firestore_sync`.`pg_medications_imported_medications_deduped`
(
  `firestore_document_id` STRING,
  `active` BOOLEAN,
  `app_id` STRING,
  `created_at` STRING,
  `created_by` STRING,
  `document_operation_instance_id` STRING,
  `execution_id` STRING,
  `host_medication_id` STRING,
  `id` STRING,
  `medication_classification` STRING,
  `medication_discontinued_date` STRING,
  `medication_dosage` STRING,
  `medication_end_date` STRING,
  `medication_form` STRING,
  `medication_frequency` STRING,
  `medication_instructions` STRING,
  `medication_medispan_id` STRING,
  `medication_name` STRING,
  `medication_route` STRING,
  `medication_start_date` STRING,
  `medication_strength` STRING,
  `medispan_id` STRING,
  `modified_at` STRING,
  `modified_by` STRING,
  `original_payload_amount` STRING,
  `original_payload_dateType` STRING,
  `original_payload_discontinueDate` STRING,
  `original_payload_dose` STRING,
  `original_payload_generateOrder` BOOLEAN,
  `original_payload_isChange` BOOLEAN,
  `original_payload_isLongStanding` BOOLEAN,
  `original_payload_isNew` BOOLEAN,
  `original_payload_medication` STRING,
  `original_payload_medicationId` INTEGER,
  `original_payload_medicationInstructions` STRING,
  `original_payload_orderDate` STRING,
  `original_payload_orderPhysicianKey` STRING,
  `original_payload_patientMedispanKey` INTEGER,
  `original_payload_patientMedispanRegistryKey` INTEGER,
  `original_payload_route` STRING,
  `original_payload_saveToMedicationProfile` BOOLEAN,
  `original_payload_startDate` STRING,
  `original_payload_strength` STRING,
  `original_payload_unitPerDose` STRING,
  `patient_id` STRING,
  `tenant_id` STRING
)
CLUSTER BY app_id, tenant_id, patient_id, modified_at;

MERGE INTO `viki-qa-app-wsky`.`firestore_sync`.`pg_medications_imported_medications_deduped` AS target 

USING (
  SELECT * FROM (
    SELECT 
      timestamp,
      event_id,
      document_name,
      operation,
      CAST(JSON_EXTRACT(data, '$.active') AS BOOLEAN) as data_active,
      JSON_EXTRACT_SCALAR(data, '$.app_id') as data_app_id,
      JSON_EXTRACT_SCALAR(data, '$.created_at') as data_created_at,
      JSON_EXTRACT_SCALAR(data, '$.created_by') as data_created_by,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_instance_id') as data_document_operation_instance_id,
      JSON_EXTRACT_SCALAR(data, '$.execution_id') as data_execution_id,
      JSON_EXTRACT_SCALAR(data, '$.host_medication_id') as data_host_medication_id,
      JSON_EXTRACT_SCALAR(data, '$.id') as data_id,
      JSON_EXTRACT_SCALAR(data, '$.medication.classification') as data_medication_classification,
      JSON_EXTRACT_SCALAR(data, '$.medication.discontinued_date') as data_medication_discontinued_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.dosage') as data_medication_dosage,
      JSON_EXTRACT_SCALAR(data, '$.medication.end_date') as data_medication_end_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.form') as data_medication_form,
      JSON_EXTRACT_SCALAR(data, '$.medication.frequency') as data_medication_frequency,
      JSON_EXTRACT_SCALAR(data, '$.medication.instructions') as data_medication_instructions,
      JSON_EXTRACT_SCALAR(data, '$.medication.medispan_id') as data_medication_medispan_id,
      JSON_EXTRACT_SCALAR(data, '$.medication.name') as data_medication_name,
      JSON_EXTRACT_SCALAR(data, '$.medication.route') as data_medication_route,
      JSON_EXTRACT_SCALAR(data, '$.medication.start_date') as data_medication_start_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.strength') as data_medication_strength,
      JSON_EXTRACT_SCALAR(data, '$.medispan_id') as data_medispan_id,
      JSON_EXTRACT_SCALAR(data, '$.modified_at') as data_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.modified_by') as data_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.amount') as data_original_payload_amount,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.dateType') as data_original_payload_dateType,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.discontinueDate') as data_original_payload_discontinueDate,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.dose') as data_original_payload_dose,
      CAST(JSON_EXTRACT(data, '$.original_payload.generateOrder') AS BOOLEAN) as data_original_payload_generateOrder,
      CAST(JSON_EXTRACT(data, '$.original_payload.isChange') AS BOOLEAN) as data_original_payload_isChange,
      CAST(JSON_EXTRACT(data, '$.original_payload.isLongStanding') AS BOOLEAN) as data_original_payload_isLongStanding,
      CAST(JSON_EXTRACT(data, '$.original_payload.isNew') AS BOOLEAN) as data_original_payload_isNew,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.medication') as data_original_payload_medication,
      CAST(JSON_EXTRACT(data, '$.original_payload.medicationId') AS INT64) as data_original_payload_medicationId,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.medicationInstructions') as data_original_payload_medicationInstructions,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.orderDate') as data_original_payload_orderDate,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.orderPhysicianKey') as data_original_payload_orderPhysicianKey,
      CAST(JSON_EXTRACT(data, '$.original_payload.patientMedispanKey') AS INT64) as data_original_payload_patientMedispanKey,
      CAST(JSON_EXTRACT(data, '$.original_payload.patientMedispanRegistryKey') AS INT64) as data_original_payload_patientMedispanRegistryKey,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.route') as data_original_payload_route,
      CAST(JSON_EXTRACT(data, '$.original_payload.saveToMedicationProfile') AS BOOLEAN) as data_original_payload_saveToMedicationProfile,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.startDate') as data_original_payload_startDate,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.strength') as data_original_payload_strength,
      JSON_EXTRACT_SCALAR(data, '$.original_payload.unitPerDose') as data_original_payload_unitPerDose,
      JSON_EXTRACT_SCALAR(data, '$.patient_id') as data_patient_id,
      JSON_EXTRACT_SCALAR(data, '$.tenant_id') as data_tenant_id,
      document_id,
      ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY timestamp DESC) as rn
    FROM `viki-qa-app-wsky`.`firestore_sync`.`pg_medications_imported_medications_raw_changelog`
    WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
  ) 
  WHERE rn = 1
) AS source 

ON target.firestore_document_id = source.document_id

WHEN MATCHED AND TIMESTAMP(target.modified_at) < TIMESTAMP(source.data_modified_at) THEN 
  UPDATE SET
      target.active = source.data_active,
      target.app_id = source.data_app_id,
      target.created_at = source.data_created_at,
      target.created_by = source.data_created_by,
      target.document_operation_instance_id = source.data_document_operation_instance_id,
      target.execution_id = source.data_execution_id,
      target.host_medication_id = source.data_host_medication_id,
      target.id = source.data_id,
      target.medication_classification = source.data_medication_classification,
      target.medication_discontinued_date = source.data_medication_discontinued_date,
      target.medication_dosage = source.data_medication_dosage,
      target.medication_end_date = source.data_medication_end_date,
      target.medication_form = source.data_medication_form,
      target.medication_frequency = source.data_medication_frequency,
      target.medication_instructions = source.data_medication_instructions,
      target.medication_medispan_id = source.data_medication_medispan_id,
      target.medication_name = source.data_medication_name,
      target.medication_route = source.data_medication_route,
      target.medication_start_date = source.data_medication_start_date,
      target.medication_strength = source.data_medication_strength,
      target.medispan_id = source.data_medispan_id,
      target.modified_at = source.data_modified_at,
      target.modified_by = source.data_modified_by,
      target.original_payload_amount = source.data_original_payload_amount,
      target.original_payload_dateType = source.data_original_payload_dateType,
      target.original_payload_discontinueDate = source.data_original_payload_discontinueDate,
      target.original_payload_dose = source.data_original_payload_dose,
      target.original_payload_generateOrder = source.data_original_payload_generateOrder,
      target.original_payload_isChange = source.data_original_payload_isChange,
      target.original_payload_isLongStanding = source.data_original_payload_isLongStanding,
      target.original_payload_isNew = source.data_original_payload_isNew,
      target.original_payload_medication = source.data_original_payload_medication,
      target.original_payload_medicationId = source.data_original_payload_medicationId,
      target.original_payload_medicationInstructions = source.data_original_payload_medicationInstructions,
      target.original_payload_orderDate = source.data_original_payload_orderDate,
      target.original_payload_orderPhysicianKey = source.data_original_payload_orderPhysicianKey,
      target.original_payload_patientMedispanKey = source.data_original_payload_patientMedispanKey,
      target.original_payload_patientMedispanRegistryKey = source.data_original_payload_patientMedispanRegistryKey,
      target.original_payload_route = source.data_original_payload_route,
      target.original_payload_saveToMedicationProfile = source.data_original_payload_saveToMedicationProfile,
      target.original_payload_startDate = source.data_original_payload_startDate,
      target.original_payload_strength = source.data_original_payload_strength,
      target.original_payload_unitPerDose = source.data_original_payload_unitPerDose,
      target.patient_id = source.data_patient_id,
      target.tenant_id = source.data_tenant_id

WHEN NOT MATCHED THEN 
  INSERT (
    firestore_document_id,
    active,
    app_id,
    created_at,
    created_by,
    document_operation_instance_id,
    execution_id,
    host_medication_id,
    id,
    medication_classification,
    medication_discontinued_date,
    medication_dosage,
    medication_end_date,
    medication_form,
    medication_frequency,
    medication_instructions,
    medication_medispan_id,
    medication_name,
    medication_route,
    medication_start_date,
    medication_strength,
    medispan_id,
    modified_at,
    modified_by,
    original_payload_amount,
    original_payload_dateType,
    original_payload_discontinueDate,
    original_payload_dose,
    original_payload_generateOrder,
    original_payload_isChange,
    original_payload_isLongStanding,
    original_payload_isNew,
    original_payload_medication,
    original_payload_medicationId,
    original_payload_medicationInstructions,
    original_payload_orderDate,
    original_payload_orderPhysicianKey,
    original_payload_patientMedispanKey,
    original_payload_patientMedispanRegistryKey,
    original_payload_route,
    original_payload_saveToMedicationProfile,
    original_payload_startDate,
    original_payload_strength,
    original_payload_unitPerDose,
    patient_id,
    tenant_id
  ) 
  VALUES (
    document_id,
    source.data_active,
    source.data_app_id,
    source.data_created_at,
    source.data_created_by,
    source.data_document_operation_instance_id,
    source.data_execution_id,
    source.data_host_medication_id,
    source.data_id,
    source.data_medication_classification,
    source.data_medication_discontinued_date,
    source.data_medication_dosage,
    source.data_medication_end_date,
    source.data_medication_form,
    source.data_medication_frequency,
    source.data_medication_instructions,
    source.data_medication_medispan_id,
    source.data_medication_name,
    source.data_medication_route,
    source.data_medication_start_date,
    source.data_medication_strength,
    source.data_medispan_id,
    source.data_modified_at,
    source.data_modified_by,
    source.data_original_payload_amount,
    source.data_original_payload_dateType,
    source.data_original_payload_discontinueDate,
    source.data_original_payload_dose,
    source.data_original_payload_generateOrder,
    source.data_original_payload_isChange,
    source.data_original_payload_isLongStanding,
    source.data_original_payload_isNew,
    source.data_original_payload_medication,
    source.data_original_payload_medicationId,
    source.data_original_payload_medicationInstructions,
    source.data_original_payload_orderDate,
    source.data_original_payload_orderPhysicianKey,
    source.data_original_payload_patientMedispanKey,
    source.data_original_payload_patientMedispanRegistryKey,
    source.data_original_payload_route,
    source.data_original_payload_saveToMedicationProfile,
    source.data_original_payload_startDate,
    source.data_original_payload_strength,
    source.data_original_payload_unitPerDose,
    source.data_patient_id,
    source.data_tenant_id
  );
