--- query firestore_sync pg_medications_user_entered_medications_raw table for last 1 hour using timestamp field and do a merge/upsert into a table "pg_medications_user_entered_medications_deduped"
CREATE TABLE IF NOT EXISTS `viki-qa-app-wsky`.`firestore_sync`.`pg_medications_user_entered_medications_deduped`
(
  `firestore_document_id` STRING,
  `app_id` STRING,
  `change_sets` STRING,
  `change_sets_changes` STRING,
  `change_sets_created_at` STRING,
  `created_at` STRING,
  `created_by` STRING,
  `deleted` BOOLEAN,
  `document_id` STRING,
  `document_operation_instance_id` STRING,
  `execution_id` STRING,
  `extracted_medication_references` STRING,
  `id` STRING,
  `medication_classification` STRING,
  `medication_discontinued_date` STRING,
  `medication_dosage` STRING,
  `medication_end_date` STRING,
  `medication_form` STRING,
  `medication_frequency` STRING,
  `medication_instructions` STRING,
  `medication_is_long_standing` BOOLEAN,
  `medication_is_nonstandard_dose` STRING,
  `medication_medispan_id` STRING,
  `medication_name` STRING,
  `medication_name_original` STRING,
  `medication_route` STRING,
  `medication_start_date` STRING,
  `medication_strength` STRING,
  `medication_profile_reconcilled_medication_id` STRING,
  `medication_status_status` STRING,
  `medication_status_status_reason` STRING,
  `medication_status_status_reason_explaination` STRING,
  `modified_at` STRING,
  `modified_by` STRING,
  `patient_id` STRING,
  `tenant_id` STRING
)
CLUSTER BY app_id, tenant_id, patient_id, modified_at;

MERGE INTO `viki-qa-app-wsky`.`firestore_sync`.`pg_medications_user_entered_medications_deduped` AS target 

USING (
  SELECT * FROM (
    SELECT 
      timestamp,
      event_id,
      document_name,
      operation,
      JSON_EXTRACT_SCALAR(data, '$.app_id') as data_app_id,
      JSON_EXTRACT_SCALAR(data, '$.change_sets') as data_change_sets,
      JSON_EXTRACT_SCALAR(data, '$.change_sets.changes') as data_change_sets_changes,
      JSON_EXTRACT_SCALAR(data, '$.change_sets.created_at') as data_change_sets_created_at,
      JSON_EXTRACT_SCALAR(data, '$.created_at') as data_created_at,
      JSON_EXTRACT_SCALAR(data, '$.created_by') as data_created_by,
      CAST(JSON_EXTRACT(data, '$.deleted') AS BOOLEAN) as data_deleted,
      JSON_EXTRACT_SCALAR(data, '$.document_id') as data_document_id,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_instance_id') as data_document_operation_instance_id,
      JSON_EXTRACT_SCALAR(data, '$.execution_id') as data_execution_id,
      JSON_EXTRACT_SCALAR(data, '$.extracted_medication_references') as data_extracted_medication_references,
      JSON_EXTRACT_SCALAR(data, '$.id') as data_id,
      JSON_EXTRACT_SCALAR(data, '$.medication.classification') as data_medication_classification,
      JSON_EXTRACT_SCALAR(data, '$.medication.discontinued_date') as data_medication_discontinued_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.dosage') as data_medication_dosage,
      JSON_EXTRACT_SCALAR(data, '$.medication.end_date') as data_medication_end_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.form') as data_medication_form,
      JSON_EXTRACT_SCALAR(data, '$.medication.frequency') as data_medication_frequency,
      JSON_EXTRACT_SCALAR(data, '$.medication.instructions') as data_medication_instructions,
      CAST(JSON_EXTRACT(data, '$.medication.is_long_standing') AS BOOLEAN) as data_medication_is_long_standing,
      JSON_EXTRACT_SCALAR(data, '$.medication.is_nonstandard_dose') as data_medication_is_nonstandard_dose,
      JSON_EXTRACT_SCALAR(data, '$.medication.medispan_id') as data_medication_medispan_id,
      JSON_EXTRACT_SCALAR(data, '$.medication.name') as data_medication_name,
      JSON_EXTRACT_SCALAR(data, '$.medication.name_original') as data_medication_name_original,
      JSON_EXTRACT_SCALAR(data, '$.medication.route') as data_medication_route,
      JSON_EXTRACT_SCALAR(data, '$.medication.start_date') as data_medication_start_date,
      JSON_EXTRACT_SCALAR(data, '$.medication.strength') as data_medication_strength,
      JSON_EXTRACT_SCALAR(data, '$.medication_profile_reconcilled_medication_id') as data_medication_profile_reconcilled_medication_id,
      JSON_EXTRACT_SCALAR(data, '$.medication_status.status') as data_medication_status_status,
      JSON_EXTRACT_SCALAR(data, '$.medication_status.status_reason') as data_medication_status_status_reason,
      JSON_EXTRACT_SCALAR(data, '$.medication_status.status_reason_explaination') as data_medication_status_status_reason_explaination,
      JSON_EXTRACT_SCALAR(data, '$.modified_at') as data_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.modified_by') as data_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.patient_id') as data_patient_id,
      JSON_EXTRACT_SCALAR(data, '$.tenant_id') as data_tenant_id,
      document_id,
      ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY timestamp DESC) as rn
    FROM `viki-qa-app-wsky`.`firestore_sync`.`pg_medications_user_entered_medications_raw_changelog`
    WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
  ) 
  WHERE rn = 1
) AS source 

ON target.firestore_document_id = source.document_id

WHEN MATCHED AND TIMESTAMP(target.modified_at) < TIMESTAMP(source.data_modified_at) THEN 
  UPDATE SET
      target.app_id = source.data_app_id,
      target.change_sets = source.data_change_sets,
      target.change_sets_changes = source.data_change_sets_changes,
      target.change_sets_created_at = source.data_change_sets_created_at,
      target.created_at = source.data_created_at,
      target.created_by = source.data_created_by,
      target.deleted = source.data_deleted,
      target.document_id = source.data_document_id,
      target.document_operation_instance_id = source.data_document_operation_instance_id,
      target.execution_id = source.data_execution_id,
      target.extracted_medication_references = source.data_extracted_medication_references,
      target.id = source.data_id,
      target.medication_classification = source.data_medication_classification,
      target.medication_discontinued_date = source.data_medication_discontinued_date,
      target.medication_dosage = source.data_medication_dosage,
      target.medication_end_date = source.data_medication_end_date,
      target.medication_form = source.data_medication_form,
      target.medication_frequency = source.data_medication_frequency,
      target.medication_instructions = source.data_medication_instructions,
      target.medication_is_long_standing = source.data_medication_is_long_standing,
      target.medication_is_nonstandard_dose = source.data_medication_is_nonstandard_dose,
      target.medication_medispan_id = source.data_medication_medispan_id,
      target.medication_name = source.data_medication_name,
      target.medication_name_original = source.data_medication_name_original,
      target.medication_route = source.data_medication_route,
      target.medication_start_date = source.data_medication_start_date,
      target.medication_strength = source.data_medication_strength,
      target.medication_profile_reconcilled_medication_id = source.data_medication_profile_reconcilled_medication_id,
      target.medication_status_status = source.data_medication_status_status,
      target.medication_status_status_reason = source.data_medication_status_status_reason,
      target.medication_status_status_reason_explaination = source.data_medication_status_status_reason_explaination,
      target.modified_at = source.data_modified_at,
      target.modified_by = source.data_modified_by,
      target.patient_id = source.data_patient_id,
      target.tenant_id = source.data_tenant_id

WHEN NOT MATCHED THEN 
  INSERT (
    firestore_document_id,
    app_id,
    change_sets,
    change_sets_changes,
    change_sets_created_at,
    created_at,
    created_by,
    deleted,
    document_id,
    document_operation_instance_id,
    execution_id,
    extracted_medication_references,
    id,
    medication_classification,
    medication_discontinued_date,
    medication_dosage,
    medication_end_date,
    medication_form,
    medication_frequency,
    medication_instructions,
    medication_is_long_standing,
    medication_is_nonstandard_dose,
    medication_medispan_id,
    medication_name,
    medication_name_original,
    medication_route,
    medication_start_date,
    medication_strength,
    medication_profile_reconcilled_medication_id,
    medication_status_status,
    medication_status_status_reason,
    medication_status_status_reason_explaination,
    modified_at,
    modified_by,
    patient_id,
    tenant_id
  ) 
  VALUES (
    document_id,
    source.data_app_id,
    source.data_change_sets,
    source.data_change_sets_changes,
    source.data_change_sets_created_at,
    source.data_created_at,
    source.data_created_by,
    source.data_deleted,
    source.data_document_id,
    source.data_document_operation_instance_id,
    source.data_execution_id,
    source.data_extracted_medication_references,
    source.data_id,
    source.data_medication_classification,
    source.data_medication_discontinued_date,
    source.data_medication_dosage,
    source.data_medication_end_date,
    source.data_medication_form,
    source.data_medication_frequency,
    source.data_medication_instructions,
    source.data_medication_is_long_standing,
    source.data_medication_is_nonstandard_dose,
    source.data_medication_medispan_id,
    source.data_medication_name,
    source.data_medication_name_original,
    source.data_medication_route,
    source.data_medication_start_date,
    source.data_medication_strength,
    source.data_medication_profile_reconcilled_medication_id,
    source.data_medication_status_status,
    source.data_medication_status_status_reason,
    source.data_medication_status_status_reason_explaination,
    source.data_modified_at,
    source.data_modified_by,
    source.data_patient_id,
    source.data_tenant_id
  );
