--- query firestore_sync pg_paperglass_commands_processed_raw table for last 1 hour using timestamp field and do a merge/upsert into a table "pg_paperglass_commands_processed_deduped"
CREATE TABLE IF NOT EXISTS `viki-qa-app-wsky`.`firestore_sync`.`pg_paperglass_commands_processed_deduped`
(
  `firestore_document_id` STRING,
  `modified_at` TIMESTAMP,
  `active_document_operation_definition_id` STRING,
  `active_document_operation_instance_id` STRING,
  `app_id` STRING,
  `created_by` STRING,
  `cross_transaction_error_strict_mode` BOOLEAN,
  `document_id` STRING,
  `document_operation_definition_id` STRING,
  `document_operation_instance_id` STRING,
  `document_operation_type` STRING,
  `ehr_token` STRING,
  `execution_id` STRING,
  `extracted_medications` STRING,
  `extraction_status` STRING,
  `extraction_type` STRING,
  `force_new_instance` BOOLEAN,
  `id` STRING,
  `idempotent_key` STRING,
  `is_test` BOOLEAN,
  `labelled_content` ARRAY<STRING>,
  `model` STRING,
  `modified_by` STRING,
  `operation_type` STRING,
  `page_id` STRING,
  `page_number` INTEGER,
  `page_text` STRING,
  `page_texts` ARRAY<STRUCT<data STRING>>,
  `patient_id` STRING,
  `pdf_parsing_strategy` INTEGER,
  `priority` STRING,
  `prompt` STRING,
  `status` STRING,
  `step_id` STRING,
  `storage_uri` STRING,
  `tenant_id` STRING,
  `test_results_app_id` STRING,
  `test_results_created_at` STRING,
  `test_results_created_by` STRING,
  `test_results_document_operation_instance_id` STRING,
  `test_results_events` ARRAY<STRING>,
  `test_results_execution_id` STRING,
  `test_results_id` STRING,
  `test_results_modified_at` STRING,
  `test_results_modified_by` STRING,
  `test_results_patient_id` STRING,
  `test_results_results_grader_results_errors` ARRAY<STRING>,
  `test_results_results_grader_results_metadata_individual` ARRAY<STRUCT<data STRING>>,
  `test_results_results_grader_results_metadata_overall_score` STRING,
  `test_results_results_grader_results_passed` BOOLEAN,
  `test_results_results_level1_results_errors` ARRAY<STRING>,
  `test_results_results_level1_results_passed` BOOLEAN,
  `test_results_results_level2_results` STRING,
  `test_results_results_level3_results` STRING,
  `test_results_results_overall_passed` BOOLEAN,
  `test_results_tenant_id` STRING,
  `test_results_test_case_created_at` STRING,
  `test_results_test_case_created_by` STRING,
  `test_results_test_case_events` ARRAY<STRING>,
  `test_results_test_case_id` STRING,
  `test_results_test_case_input_data_document_id` STRING,
  `test_results_test_case_input_data_token` STRING,
  `test_results_test_case_modified_at` STRING,
  `test_results_test_case_modified_by` STRING,
  `test_results_test_case_name` STRING,
  `test_results_test_case_test_conditions_list_of_medispan_ids` ARRAY<STRING>,
  `test_results_test_case_test_conditions_max_duration_of_test_execution` INTEGER,
  `test_results_test_case_test_conditions_medispan_matched_count` INTEGER,
  `test_results_test_case_test_conditions_minimum_overall_score` STRING,
  `test_results_test_case_test_conditions_total_count` INTEGER,
  `test_results_test_case_test_conditions_unlisted_count` INTEGER,
  `test_results_test_case_test_type` STRING,
  `token` STRING,
  `type` STRING,
  `user_entered_medication` STRING
)
CLUSTER BY app_id, tenant_id, patient_id, modified_at;

MERGE INTO `viki-qa-app-wsky`.`firestore_sync`.`pg_paperglass_commands_processed_deduped` AS target 

USING (
  SELECT * FROM (
    SELECT 
      timestamp,
      event_id,
      document_name,
      operation,
      JSON_EXTRACT_SCALAR(data, '$.active_document_operation_definition_id') as data_active_document_operation_definition_id,
      JSON_EXTRACT_SCALAR(data, '$.active_document_operation_instance_id') as data_active_document_operation_instance_id,
      JSON_EXTRACT_SCALAR(data, '$.app_id') as data_app_id,
      JSON_EXTRACT_SCALAR(data, '$.created_by') as data_created_by,
      CAST(JSON_EXTRACT(data, '$.cross_transaction_error_strict_mode') AS BOOLEAN) as data_cross_transaction_error_strict_mode,
      JSON_EXTRACT_SCALAR(data, '$.document_id') as data_document_id,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_definition_id') as data_document_operation_definition_id,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_instance_id') as data_document_operation_instance_id,
      JSON_EXTRACT_SCALAR(data, '$.document_operation_type') as data_document_operation_type,
      JSON_EXTRACT_SCALAR(data, '$.ehr_token') as data_ehr_token,
      JSON_EXTRACT_SCALAR(data, '$.execution_id') as data_execution_id,
      JSON_EXTRACT_SCALAR(data, '$.extracted_medications') as data_extracted_medications,
      JSON_EXTRACT_SCALAR(data, '$.extraction_status') as data_extraction_status,
      JSON_EXTRACT_SCALAR(data, '$.extraction_type') as data_extraction_type,
      CAST(JSON_EXTRACT(data, '$.force_new_instance') AS BOOLEAN) as data_force_new_instance,
      JSON_EXTRACT_SCALAR(data, '$.id') as data_id,
      JSON_EXTRACT_SCALAR(data, '$.idempotent_key') as data_idempotent_key,
      CAST(JSON_EXTRACT(data, '$.is_test') AS BOOLEAN) as data_is_test,
      JSON_EXTRACT_ARRAY(data, '$.labelled_content') as data_labelled_content,
      JSON_EXTRACT_SCALAR(data, '$.model') as data_model,
      JSON_EXTRACT_SCALAR(data, '$.modified_by') as data_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.operation_type') as data_operation_type,
      JSON_EXTRACT_SCALAR(data, '$.page_id') as data_page_id,
      CAST(JSON_EXTRACT(data, '$.page_number') AS INT64) as data_page_number,
      JSON_EXTRACT_SCALAR(data, '$.page_text') as data_page_text,
      ARRAY(SELECT STRUCT(med as data) FROM UNNEST(JSON_EXTRACT_ARRAY(data, '$.page_texts')) as med) as data_page_texts,
      JSON_EXTRACT_SCALAR(data, '$.patient_id') as data_patient_id,
      CAST(JSON_EXTRACT(data, '$.pdf_parsing_strategy') AS INT64) as data_pdf_parsing_strategy,
      JSON_EXTRACT_SCALAR(data, '$.priority') as data_priority,
      JSON_EXTRACT_SCALAR(data, '$.prompt') as data_prompt,
      JSON_EXTRACT_SCALAR(data, '$.status') as data_status,
      JSON_EXTRACT_SCALAR(data, '$.step_id') as data_step_id,
      JSON_EXTRACT_SCALAR(data, '$.storage_uri') as data_storage_uri,
      JSON_EXTRACT_SCALAR(data, '$.tenant_id') as data_tenant_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.app_id') as data_test_results_app_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.created_at') as data_test_results_created_at,
      JSON_EXTRACT_SCALAR(data, '$.test_results.created_by') as data_test_results_created_by,
      JSON_EXTRACT_SCALAR(data, '$.test_results.document_operation_instance_id') as data_test_results_document_operation_instance_id,
      JSON_EXTRACT_ARRAY(data, '$.test_results.events') as data_test_results_events,
      JSON_EXTRACT_SCALAR(data, '$.test_results.execution_id') as data_test_results_execution_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.id') as data_test_results_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.modified_at') as data_test_results_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.test_results.modified_by') as data_test_results_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.test_results.patient_id') as data_test_results_patient_id,
      JSON_EXTRACT_ARRAY(data, '$.test_results.results.grader_results.errors') as data_test_results_results_grader_results_errors,
      ARRAY(SELECT STRUCT(med as data) FROM UNNEST(JSON_EXTRACT_ARRAY(data, '$.test_results.results.grader_results.metadata.individual')) as med) as data_test_results_results_grader_results_metadata_individual,
      JSON_EXTRACT_SCALAR(data, '$.test_results.results.grader_results.metadata.overall_score') as data_test_results_results_grader_results_metadata_overall_score,
      CAST(JSON_EXTRACT(data, '$.test_results.results.grader_results.passed') AS BOOLEAN) as data_test_results_results_grader_results_passed,
      JSON_EXTRACT_ARRAY(data, '$.test_results.results.level1_results.errors') as data_test_results_results_level1_results_errors,
      CAST(JSON_EXTRACT(data, '$.test_results.results.level1_results.passed') AS BOOLEAN) as data_test_results_results_level1_results_passed,
      JSON_EXTRACT_SCALAR(data, '$.test_results.results.level2_results') as data_test_results_results_level2_results,
      JSON_EXTRACT_SCALAR(data, '$.test_results.results.level3_results') as data_test_results_results_level3_results,
      CAST(JSON_EXTRACT(data, '$.test_results.results.overall_passed') AS BOOLEAN) as data_test_results_results_overall_passed,
      JSON_EXTRACT_SCALAR(data, '$.test_results.tenant_id') as data_test_results_tenant_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.created_at') as data_test_results_test_case_created_at,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.created_by') as data_test_results_test_case_created_by,
      JSON_EXTRACT_ARRAY(data, '$.test_results.test_case.events') as data_test_results_test_case_events,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.id') as data_test_results_test_case_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.input_data.document_id') as data_test_results_test_case_input_data_document_id,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.input_data.token') as data_test_results_test_case_input_data_token,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.modified_at') as data_test_results_test_case_modified_at,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.modified_by') as data_test_results_test_case_modified_by,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.name') as data_test_results_test_case_name,
      JSON_EXTRACT_ARRAY(data, '$.test_results.test_case.test_conditions.list_of_medispan_ids') as data_test_results_test_case_test_conditions_list_of_medispan_ids,
      CAST(JSON_EXTRACT(data, '$.test_results.test_case.test_conditions.max_duration_of_test_execution') AS INT64) as data_test_results_test_case_test_conditions_max_duration_of_test_execution,
      CAST(JSON_EXTRACT(data, '$.test_results.test_case.test_conditions.medispan_matched_count') AS INT64) as data_test_results_test_case_test_conditions_medispan_matched_count,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.test_conditions.minimum_overall_score') as data_test_results_test_case_test_conditions_minimum_overall_score,
      CAST(JSON_EXTRACT(data, '$.test_results.test_case.test_conditions.total_count') AS INT64) as data_test_results_test_case_test_conditions_total_count,
      CAST(JSON_EXTRACT(data, '$.test_results.test_case.test_conditions.unlisted_count') AS INT64) as data_test_results_test_case_test_conditions_unlisted_count,
      JSON_EXTRACT_SCALAR(data, '$.test_results.test_case.test_type') as data_test_results_test_case_test_type,
      JSON_EXTRACT_SCALAR(data, '$.token') as data_token,
      JSON_EXTRACT_SCALAR(data, '$.type') as data_type,
      JSON_EXTRACT_SCALAR(data, '$.user_entered_medication') as data_user_entered_medication,
      document_id,
      ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY timestamp DESC) as rn
    FROM `viki-qa-app-wsky`.`firestore_sync`.`pg_paperglass_commands_processed_raw_changelog`
    WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
  ) 
  WHERE rn = 1
) AS source 

ON target.firestore_document_id = source.document_id

WHEN MATCHED AND TIMESTAMP(target.modified_at) < TIMESTAMP(source.data_modified_at) THEN 
  UPDATE SET
      target.active_document_operation_definition_id = source.data_active_document_operation_definition_id,
      target.active_document_operation_instance_id = source.data_active_document_operation_instance_id,
      target.app_id = source.data_app_id,
      target.created_by = source.data_created_by,
      target.cross_transaction_error_strict_mode = source.data_cross_transaction_error_strict_mode,
      target.document_id = source.data_document_id,
      target.document_operation_definition_id = source.data_document_operation_definition_id,
      target.document_operation_instance_id = source.data_document_operation_instance_id,
      target.document_operation_type = source.data_document_operation_type,
      target.ehr_token = source.data_ehr_token,
      target.execution_id = source.data_execution_id,
      target.extracted_medications = source.data_extracted_medications,
      target.extraction_status = source.data_extraction_status,
      target.extraction_type = source.data_extraction_type,
      target.force_new_instance = source.data_force_new_instance,
      target.id = source.data_id,
      target.idempotent_key = source.data_idempotent_key,
      target.is_test = source.data_is_test,
      target.labelled_content = source.data_labelled_content,
      target.model = source.data_model,
      target.modified_by = source.data_modified_by,
      target.operation_type = source.data_operation_type,
      target.page_id = source.data_page_id,
      target.page_number = source.data_page_number,
      target.page_text = source.data_page_text,
      target.page_texts = source.data_page_texts,
      target.patient_id = source.data_patient_id,
      target.pdf_parsing_strategy = source.data_pdf_parsing_strategy,
      target.priority = source.data_priority,
      target.prompt = source.data_prompt,
      target.status = source.data_status,
      target.step_id = source.data_step_id,
      target.storage_uri = source.data_storage_uri,
      target.tenant_id = source.data_tenant_id,
      target.test_results_app_id = source.data_test_results_app_id,
      target.test_results_created_at = source.data_test_results_created_at,
      target.test_results_created_by = source.data_test_results_created_by,
      target.test_results_document_operation_instance_id = source.data_test_results_document_operation_instance_id,
      target.test_results_events = source.data_test_results_events,
      target.test_results_execution_id = source.data_test_results_execution_id,
      target.test_results_id = source.data_test_results_id,
      target.test_results_modified_at = source.data_test_results_modified_at,
      target.test_results_modified_by = source.data_test_results_modified_by,
      target.test_results_patient_id = source.data_test_results_patient_id,
      target.test_results_results_grader_results_errors = source.data_test_results_results_grader_results_errors,
      target.test_results_results_grader_results_metadata_individual = source.data_test_results_results_grader_results_metadata_individual,
      target.test_results_results_grader_results_metadata_overall_score = source.data_test_results_results_grader_results_metadata_overall_score,
      target.test_results_results_grader_results_passed = source.data_test_results_results_grader_results_passed,
      target.test_results_results_level1_results_errors = source.data_test_results_results_level1_results_errors,
      target.test_results_results_level1_results_passed = source.data_test_results_results_level1_results_passed,
      target.test_results_results_level2_results = source.data_test_results_results_level2_results,
      target.test_results_results_level3_results = source.data_test_results_results_level3_results,
      target.test_results_results_overall_passed = source.data_test_results_results_overall_passed,
      target.test_results_tenant_id = source.data_test_results_tenant_id,
      target.test_results_test_case_created_at = source.data_test_results_test_case_created_at,
      target.test_results_test_case_created_by = source.data_test_results_test_case_created_by,
      target.test_results_test_case_events = source.data_test_results_test_case_events,
      target.test_results_test_case_id = source.data_test_results_test_case_id,
      target.test_results_test_case_input_data_document_id = source.data_test_results_test_case_input_data_document_id,
      target.test_results_test_case_input_data_token = source.data_test_results_test_case_input_data_token,
      target.test_results_test_case_modified_at = source.data_test_results_test_case_modified_at,
      target.test_results_test_case_modified_by = source.data_test_results_test_case_modified_by,
      target.test_results_test_case_name = source.data_test_results_test_case_name,
      target.test_results_test_case_test_conditions_list_of_medispan_ids = source.data_test_results_test_case_test_conditions_list_of_medispan_ids,
      target.test_results_test_case_test_conditions_max_duration_of_test_execution = source.data_test_results_test_case_test_conditions_max_duration_of_test_execution,
      target.test_results_test_case_test_conditions_medispan_matched_count = source.data_test_results_test_case_test_conditions_medispan_matched_count,
      target.test_results_test_case_test_conditions_minimum_overall_score = source.data_test_results_test_case_test_conditions_minimum_overall_score,
      target.test_results_test_case_test_conditions_total_count = source.data_test_results_test_case_test_conditions_total_count,
      target.test_results_test_case_test_conditions_unlisted_count = source.data_test_results_test_case_test_conditions_unlisted_count,
      target.test_results_test_case_test_type = source.data_test_results_test_case_test_type,
      target.token = source.data_token,
      target.type = source.data_type,
      target.user_entered_medication = source.data_user_entered_medication

WHEN NOT MATCHED THEN 
  INSERT (
    firestore_document_id,
    active_document_operation_definition_id,
    active_document_operation_instance_id,
    app_id,
    created_by,
    cross_transaction_error_strict_mode,
    document_id,
    document_operation_definition_id,
    document_operation_instance_id,
    document_operation_type,
    ehr_token,
    execution_id,
    extracted_medications,
    extraction_status,
    extraction_type,
    force_new_instance,
    id,
    idempotent_key,
    is_test,
    labelled_content,
    model,
    modified_by,
    operation_type,
    page_id,
    page_number,
    page_text,
    page_texts,
    patient_id,
    pdf_parsing_strategy,
    priority,
    prompt,
    status,
    step_id,
    storage_uri,
    tenant_id,
    test_results_app_id,
    test_results_created_at,
    test_results_created_by,
    test_results_document_operation_instance_id,
    test_results_events,
    test_results_execution_id,
    test_results_id,
    test_results_modified_at,
    test_results_modified_by,
    test_results_patient_id,
    test_results_results_grader_results_errors,
    test_results_results_grader_results_metadata_individual,
    test_results_results_grader_results_metadata_overall_score,
    test_results_results_grader_results_passed,
    test_results_results_level1_results_errors,
    test_results_results_level1_results_passed,
    test_results_results_level2_results,
    test_results_results_level3_results,
    test_results_results_overall_passed,
    test_results_tenant_id,
    test_results_test_case_created_at,
    test_results_test_case_created_by,
    test_results_test_case_events,
    test_results_test_case_id,
    test_results_test_case_input_data_document_id,
    test_results_test_case_input_data_token,
    test_results_test_case_modified_at,
    test_results_test_case_modified_by,
    test_results_test_case_name,
    test_results_test_case_test_conditions_list_of_medispan_ids,
    test_results_test_case_test_conditions_max_duration_of_test_execution,
    test_results_test_case_test_conditions_medispan_matched_count,
    test_results_test_case_test_conditions_minimum_overall_score,
    test_results_test_case_test_conditions_total_count,
    test_results_test_case_test_conditions_unlisted_count,
    test_results_test_case_test_type,
    token,
    type,
    user_entered_medication
  ) 
  VALUES (
    document_id,
    source.data_active_document_operation_definition_id,
    source.data_active_document_operation_instance_id,
    source.data_app_id,
    source.data_created_by,
    source.data_cross_transaction_error_strict_mode,
    source.data_document_id,
    source.data_document_operation_definition_id,
    source.data_document_operation_instance_id,
    source.data_document_operation_type,
    source.data_ehr_token,
    source.data_execution_id,
    source.data_extracted_medications,
    source.data_extraction_status,
    source.data_extraction_type,
    source.data_force_new_instance,
    source.data_id,
    source.data_idempotent_key,
    source.data_is_test,
    source.data_labelled_content,
    source.data_model,
    source.data_modified_by,
    source.data_operation_type,
    source.data_page_id,
    source.data_page_number,
    source.data_page_text,
    source.data_page_texts,
    source.data_patient_id,
    source.data_pdf_parsing_strategy,
    source.data_priority,
    source.data_prompt,
    source.data_status,
    source.data_step_id,
    source.data_storage_uri,
    source.data_tenant_id,
    source.data_test_results_app_id,
    source.data_test_results_created_at,
    source.data_test_results_created_by,
    source.data_test_results_document_operation_instance_id,
    source.data_test_results_events,
    source.data_test_results_execution_id,
    source.data_test_results_id,
    source.data_test_results_modified_at,
    source.data_test_results_modified_by,
    source.data_test_results_patient_id,
    source.data_test_results_results_grader_results_errors,
    source.data_test_results_results_grader_results_metadata_individual,
    source.data_test_results_results_grader_results_metadata_overall_score,
    source.data_test_results_results_grader_results_passed,
    source.data_test_results_results_level1_results_errors,
    source.data_test_results_results_level1_results_passed,
    source.data_test_results_results_level2_results,
    source.data_test_results_results_level3_results,
    source.data_test_results_results_overall_passed,
    source.data_test_results_tenant_id,
    source.data_test_results_test_case_created_at,
    source.data_test_results_test_case_created_by,
    source.data_test_results_test_case_events,
    source.data_test_results_test_case_id,
    source.data_test_results_test_case_input_data_document_id,
    source.data_test_results_test_case_input_data_token,
    source.data_test_results_test_case_modified_at,
    source.data_test_results_test_case_modified_by,
    source.data_test_results_test_case_name,
    source.data_test_results_test_case_test_conditions_list_of_medispan_ids,
    source.data_test_results_test_case_test_conditions_max_duration_of_test_execution,
    source.data_test_results_test_case_test_conditions_medispan_matched_count,
    source.data_test_results_test_case_test_conditions_minimum_overall_score,
    source.data_test_results_test_case_test_conditions_total_count,
    source.data_test_results_test_case_test_conditions_unlisted_count,
    source.data_test_results_test_case_test_type,
    source.data_token,
    source.data_type,
    source.data_user_entered_medication
  );
